### ISSUE TITLE
about parse advertisement data

### ISSUE THREAD

**Issue by yubozhao** [randdusing/cordova-plugin-bluetoothle#110]
Hi @randdusing 
Just curious, do you have a good recommendation of who to parse advertisement data that got back from scanning?

I am working on a project that broadcast app data through advertisment when you scan it to avoid the extra steps of connect & discover.  I am pretty lost in the whole hex data thing, could you give me some leads of how would I solve it?

**Comment by Tomino2112** [comment]
@randdusing Any idea how many bytes can you add?

**Comment by randdusing** [comment]
@Tomino2112 I haven't played with the server/advertising side yet, but it's probably limited to 20 bytes like other BluetoothLE packets.

The next version will include more advertisement data for iOS devices.

**Comment by randdusing** [comment]
Improved advertisement data parsing is now available in v3 for iOS.
