### ISSUE TITLE
Scanning callback consistency

### ISSUE THREAD

**Issue by mrquincle** [randdusing/cordova-plugin-bluetoothle#117]
It would be great if the plugin would provide a consistent interface to the - admittedly dubiously - implementations on the different Android devices.

Depending on the chipset used [see this Android issue](https://code.google.com/p/android/issues/detail?id=65863) there is only a single advertisement packet that arrives from a (in principle) connectable device, or a bunch of them. It would be great if there would be a way to use this library that if the chip involved does not initiate a scan request after an adv packet, this will be done by the library. This should only be done by devices that have the Qualcomm, such as the Nexus 4 and the Nexus 7.

It would be really great to have this library taking care of the consistency in these callbacks when adv packets are received from the same (connectable) device.

**Comment by randdusing** [comment]
@mrquincle Do you think these options will help: http://developer.android.com/reference/android/bluetooth/le/ScanSettings.html? A pull request was just made to make use of the updated scanning functionality in API 21. I want to make a few changes and test a bit, but it should be released within a few days.

**Comment by randdusing** [comment]
@mrquincle Forgot to mention it's released now.

**Comment by randdusing** [comment]
Please re-open if the new scan functionality doesn't resolve the issue.
