### ISSUE TITLE
Advertisement raw data differences between Android and IOS

### ISSUE THREAD

**Issue by diverJohn** [randdusing/cordova-plugin-bluetoothle#121]
Rand,

The Android version of my app is up and running and now I am integrating the IOS version.  My app pulls some manufacturer specific data from the advertising packet but the raw advertising data is returned differently between the Android and IOS.  I need to read the manufacturer specific data, i.e. "7 ff 0 1 1 0 25 29", shown in my Android raw data below.  The IOS seems to return only "0 1 1 0 25 29".   Is this an issue with the plugin or just the way IOS returns advertising data?

Android:
Stringify: {\"advertisement\":\"AgEGEQYbxdWlAgAttOMRAPBgCtZIB/8AAQEAJSkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\",\"status\":\"scanResult\",\"address\":\"D0:5F:B8:44:4A:E1\",\"rssi\":-66}"

Raw Advertisement Data: 
Msg Advertise: 2 1 6 11 6 1b c5 d5 a5 2 0 2d b4 e3 11 0 f0 60 a d6 48 7 ff 0 1 1 0 25 29 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"

IOS:
Stringify:
{\"status\":\"scanResult\",\"name\":\"Nextivity Bridge\",\"advertisement\":\"AAEBACUp\",\"address\":\"1CFBDB83-B643-F9DC-1425-493C4A549F64\",\"rssi\":-65}"

Raw Advertisement Data:
Msg Advertise: 0 1 1 0 25 29 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"

**Comment by diverJohn** [comment]
Please add the other keys, specifically the UUID.    I now have to filter the 128-bit UUID at the application level for Android per https://code.google.com/p/android/issues/detail?id=59490&q=BLE&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars.   
I could not get the 128-bit UUID filter to work on IOS either so now I am looking for some other custom data on IOS but would rather use the 128-bit UUID like I am doing on Android.

**Comment by randdusing** [comment]
Noted, I'll try to add this before the next update.

**Comment by randdusing** [comment]
Oops, forgot about this. I'll try to add tonight.

**Comment by kgillespieanaren** [comment]
For android would it make sense to write some code to decode the raw advertising data and add the same keys as they would show up in the iOS return values?

So we can keep a consistency between the two so you can use the same code on both platforms? I wonder what it looks like for Windows Phone.

**Comment by quilkin** [comment]
In the docs it says that the data returned from a scan includes raw manufacturing data in the advertisement:
            {
                "status": "scanResult",
                "advertisement": "awArG05L",
                "rssi": -58,
                "name": "Polar H7 3B321015",
                "address": "ECC037FD-72AE-AFC5-9213-CA785B3B5C63"
            }
I'm getting the "advertisement" string for Android but not for iOS (although all the other strings are present). I want to use it as a workaround for not being able to get the MAC address for iOS (as you suggest elsewhere). Am I doing something wrong with initialising or Start Scan?

**Comment by hervethouzard** [comment]
Hello,

Advertisment data for iOs are not available (verifyed with iOs 9 and the plugin in its current version at the time of writing this comment). Is this something you think that you will have time to add ?

Bye,
Hervé

**Comment by randdusing** [comment]
@hervethouzard I actually wrote the code a few weeks ago, but didn't add it to the actual plugin. I'll add this to the next release, which should happen in a few days.

**Comment by randdusing** [comment]
This is now in v3
