### ISSUE TITLE
Reconnect takes a long time

### ISSUE THREAD

**Issue by quilkin** [randdusing/cordova-plugin-bluetoothle#123]
Getting on fine with this library, thanks - connect, discover services etc all working well. But after using 'disconnect' and then trying 'reconnect', I get 'reconnecting' status but then nothing for 2-3 minutes - then the reconnection happens! The devices are still advertising during this time.

**Comment by randdusing** [comment]
Still experiencing this issue? I couldn't recreate it, but I'm only connecting to a heart rate monitor.

**Comment by quilkin** [comment]
I'm always calling close() after disconnect  and that seems a usable workaround for now.

**Comment by hervethouzard** [comment]
Hello,

With iOs I have no problem to reconnect using the reconnect() method.
Concerning Android :
- on Android 4.4.4, I have to close() then reconnect().
- on Android 5.0.1 *I do not have* to use reconnnect() (using it cause the program not to run anymore)

Bye,
Hervé

**Comment by randdusing** [comment]
@quilkin @hervethouzard Do you still have this issue? I cleaned up the connection code a bit in 3.0.0 including the removal of the connecting and disconnecting events.

**Comment by quilkin** [comment]
Sorry, I'm no longer working on this as my sponsor pulled out. Thanks for the help anyway.
