### ISSUE TITLE
Server Side Support

### ISSUE THREAD

**Issue by randdusing** [randdusing/cordova-plugin-bluetoothle#15]
I don't have immediate plans to add server side support, but I'd like to eventually add this for completeness.

**Comment by titoasty** [comment]
Now that Android has full support, I think that would be a great enhancement !!! (and I really need it ! I could help you with android version, and perhaps windows phone too)

**Comment by roeku** [comment]
Any progress on connecting to 1 host with multiple clients?

**Comment by randdusing** [comment]
Hi Roeku, I've made some progress mostly on iOS. Are you more interested in iOS or Android? Perhaps I can release a branch sometime this week.

**Comment by roeku** [comment]
Hmm, I'm working on android, though could find some iOS devices as alternate clients. I'd much appreciate the update.

**Comment by randdusing** [comment]
Sorry for the delay, Android and iOS have some implementation differences. I think I'm just going to release something as soon as possible and then worry about making the Javascript layer cleaner and more generic in the future. Currently, you may need to a lot of platform specific code.

**Comment by randdusing** [comment]
I've added server support for iOS in [4.0.0-dev branch](https://github.com/randdusing/cordova-plugin-bluetoothle/tree/4.0.0-dev). It would be nice to have some other users test it out.

Warnings:
- I don't recommend using this in production.
- Android is completely untested.
- Method names / overall process is subject to change, especially once I align iOS and Android.
- Documentation isn't very good right now. Check out the Angular wrapper's example in the [4.0.0-dev branch](https://github.com/randdusing/ng-cordova-bluetoothle/tree/4.0.0-dev).

**Comment by randdusing** [comment]
Android is now pretty stable. I'd appreciate any feedback. If you run into any problems, please open a new issue.
