### ISSUE TITLE
Android Crash on Initialisation / Scanning

### ISSUE THREAD

**Issue by maximilianloy** [randdusing/cordova-plugin-bluetoothle#219]
Hi,

Once in a while I see a crash of the app as soon as it initialises / starts scanning.
I can not reproduce it but would like to post the crash log here in case it makes sense to someone.

My device is a Nexus 5 running Android 6.0

[bt-crash-log.txt](https://github.com/randdusing/BluetoothLE/files/59710/bt-crash-log.txt)

**Comment by randdusing** [comment]
I'm not sure what the BluetoothPairingDialog is about, but I believe the plugin related errors are from a race condition. Still trying to figure that one out...

**Comment by randdusing** [comment]
Still seeing this issue? I took another look at your crash log and it looks to be related to an RSSI call. Are you calling that anywhere?

**Comment by randdusing** [comment]
I believe this should be fixed in v3 with some changes to the scan locking mechanism. Let me know if it still exists.
