### ISSUE TITLE
Data transfer

### ISSUE THREAD

**Issue by LNTWave** [randdusing/cordova-plugin-bluetoothle#228]
Hi,

Basically I'm trying to increase the throughput of data transfer using BLE. When I try to send a junk of data (>20byte) to the plugin, the data received at the receiving end is not complete. It is always equal to 20byte. 
On the other hand, if I try to alter your plugin code, such a way it splits the data into 20bytes, am unable to connect to my BLE device. Possibly due to improper data. Could you suggest on this issue?

**Comment by randdusing** [comment]
Hi @LNTWave, I would try splitting the data into 20 byte packets from the app level.

**Comment by OrenLederman** [comment]
The 20 bytes limit is because of the Bluetooth LE protocol. I think it's increased in Bluetooth 4.2, but it doesn't seem to be supported by all phones.

**Comment by randdusing** [comment]
@LNTWave Check out the writeQ functions that I added recently with 3.2.0. This will split the packets and write them as fast as possible on Android and iOS. You'll need to install directly form GitHub since it's not in NPM yet.
