### ISSUE TITLE
Intel XDK debug module

### ISSUE THREAD

**Issue by wshaheer** [randdusing/cordova-plugin-bluetoothle#239]
I've been able to build the debug module using version 2.4.0 of the plugin, however, after upgrading to version 3.0.1, it fails to install the plugin on the module
![screen shot 2016-02-18 at 10 56 27 am](https://cloud.githubusercontent.com/assets/13646429/13149138/509122ec-d62e-11e5-8b6f-75f1b76f0573.png)

**Comment by randdusing** [comment]
Latest version of the plugin uses Android API 23 and Cordova Android 5.0, which may be causing problems. I'm not familiar with Intel XDK, but it may not support those yet.
