### ISSUE TITLE
Polar H7

### ISSUE THREAD

**Issue by goariel10** [randdusing/cordova-plugin-bluetoothle#245]
hi, someone know how to convert the suscribe value   (FlHMAsMC, FlKtAg==) to integer on javascript?

sample data 

{"status":"subscribedResult","value":"**FlHMAsMC**","characteristic":"2a37","name":"Polar H7 81858E1F","service":"180d","address":"F36E18D9-BFE3-0ED7-85AF-0EA32AD0B7B7"}

{"status":"subscribedResult","value":"**FlKtAg==**","characteristic":"2a37","name":"Polar H7 81858E1F","service":"180d","address":"F36E18D9-BFE3-0ED7-85AF-0EA32AD0B7B7"}

thanks a lot :)

**Comment by randdusing** [comment]
Check out the Data Parsing Example in the readme. It should be exactly what you need.
