### ISSUE TITLE
Syntax error in plugin.xml

### ISSUE THREAD

**Issue by chriswoodle** [randdusing/cordova-plugin-bluetoothle#255]
Seems to be an error on line 66

**Comment by randdusing** [comment]
What version of Cordova are you on? And what platforms do you have added?

**Comment by chriswoodle** [comment]
I'm using visual studio tools for apache cordova, Cordova version 6.0.0, android, ios, windows

![Imgur](http://i.imgur.com/iKUzHWI.png)

I removed the "<" and it worked fine.

**Comment by randdusing** [comment]
Hmm, it's not valid XML according to an online XML validator, but Cordova's documentation says it should work: https://cordova.apache.org/docs/en/5.0.0/plugin_ref/spec.html See the config-file section.

Is it just a validation error within VS, or does it prevent the app from building?

**Comment by chriswoodle** [comment]
Agreed,
Using visual studio to build it does fail building, (Character '<', hexadecimal value 0x3c is illegal in XML attribute values.)

Seems to build fine from the cli (6.1.0)

**Comment by randdusing** [comment]
May want to submit a bug to VS Tools for Cordova

**Comment by chriswoodle** [comment]
Ok, sounds good
