### ISSUE TITLE
Queue Subscribes

### ISSUE THREAD

**Issue by RangerMauve** [randdusing/cordova-plugin-bluetoothle#263]
I've been using the master branch for connecting to my device, and reading/writing seems to queue up just fine. However, I'm experiencing issues subscribing to a certain notification. Specifically, it errors out [here](https://github.com/randdusing/cordova-plugin-bluetoothle/blob/master/src/android/BluetoothLePlugin.java#L1589) saying that it was "Unable to write descriptor". Now, I have all my writes/reads/subscribes happening at almost the same time because this was handled properly [with queuing](https://github.com/don/cordova-plugin-ble-central/blob/master/src/android/BLECentralPlugin.java#L271) in the library I had previously worked with.

I'm assuming it's an issue with the `subscribe` failing because either one of my reads or writes are happening at the same time it's attempting to write to the descriptor.

I'm testing this on Android 5.1.1, with cordova platform 5.1.1.

Would a PR be welcome to add this feature? Are there any workarounds I can take in the meantime? (I'm thinking I'll just add an artificial delay to the subscribe call in the API wrapper I made)

**Comment by randdusing** [comment]
@RangerMauve Thanks for trying out the master branch. A PR would be welcome, but I may be able to work on it over the next few days. It should be pretty straightforward to recreate the functionality for read/writeDescriptors and subscribe/unsubscribe.

In the meantime, a delay is your best option even if it's a bit hacky. If you're using the Angular wrapper, you could also try chaining the promises together.

**Comment by RangerMauve** [comment]
Adding a delay of a few seconds seems to have done it for now. I'll see if I have time to allocate to this tomorrow if you haven't gotten to it by then. Lots of other stuff piling up at the same time, sadly. :P

**Comment by randdusing** [comment]
I'm making some updates as we speak and will be testing later today. If all goes well, should see it merged to master branch sometime tonight.

**Comment by RangerMauve** [comment]
Perfect. Then I'll give it a field test tomorrow morning.

**Comment by randdusing** [comment]
@RangerMauve I updated master with queueing support for all the operations. Let me know if you run into any issues.

**Comment by RangerMauve** [comment]
Bleh, I have to take care of some other things first. Will probably have some time later this afternoon to devote to this again.

**Comment by RangerMauve** [comment]
I've got the code currently in master running out in the wild for a couple of days now and it's all running smoothly as far as I can tell. Thanks!

**Comment by randdusing** [comment]
Cool, glad it's working out!
