### ISSUE TITLE
iOS Memory Warning

### ISSUE THREAD

**Issue by tfmontague** [randdusing/cordova-plugin-bluetoothle#269]

**Comment by randdusing** [comment]
Perhaps related to #268 ? Is the app doing anything else that may be putting extra load on the device?

**Comment by tfmontague** [comment]
I think the problem is that the Central and the Peripheral can't be initialized at the same time. And I think that they fight for the same resource, which results in a Memory warning. I was able to to fix the issue, by invoking the `initialize` function after the `initializePeripheral` callback returned.

The [ng-cordova-bluetooh](https://github.com/randdusing/ng-cordova-bluetoothle) app is built in such a way that the user needs to toggle between Central and Peripheral views, and therefore it's unable to test this edge case - i.e. when `initialize` and `initializePeripheral` buttons are pressed together.

**This works!**
```
var cbSuccess = function () {
  bluetoothle.initialize(...);
};
...
bluetoothle.initializePeripheral(cbSuccess, cbError, params); 
```

**This doesn't work!**
```
bluetoothle.initializePeripheral(...); 
bluetoothle.initialize(...);
```

**Comment by randdusing** [comment]
I recommend the first way. In one of the examples of the example app, I call initialize and then initializePeripheral in the success, so I never ran into the memory warning issue. Probably the best thing I can do now is add this to the documentation.

**Comment by randdusing** [comment]
Hmm, I'm not able to recreate this on my iPad Air or iPhone 5S. Can you see how much memory is being used? The memory doesn't change between my default example app, and the example app where initialize and initializePeripheral are automatically called back to back.

**Comment by tfmontague** [comment]
It's clear there's a memory leak.

**This works!**
```
var cbSuccess = function () {
  bluetoothle.initialize(...);
};
bluetoothle.initializePeripheral(cbSuccess, cbError, params); 
```
![sync](https://cloud.githubusercontent.com/assets/1149793/15070817/cc3b763c-133b-11e6-9b6f-6fe8c3c5c966.png)

**This doesn't work!**
```
bluetoothle.initializePeripheral(...); 
bluetoothle.initialize(...);
```
![async](https://cloud.githubusercontent.com/assets/1149793/15070814/c692c46a-133b-11e6-8b14-90da1f63b422.png)

**Comment by tfmontague** [comment]
I wonder if it's my version of Xcode (I'm using a beta 3 version of 7.1)... the odd part is that when I use the Instrument app to profile the Leaks (rather than the memory chart provided by Xcode) - there aren't any leaks found... and the app seems to magically work afterwards.
![leaks](https://cloud.githubusercontent.com/assets/1149793/15071977/87567b62-1344-11e6-848d-0a97443acee7.png)

**Comment by randdusing** [comment]
I'm using Version 7.3 (7D175). Curious if you encounter the same issue if you update.
