### ISSUE TITLE
iOS - Unrecognized Selector Error

### ISSUE THREAD

**Issue by tfmontague** [randdusing/cordova-plugin-bluetoothle#273]
Got the following error from `bluetoothle.characteristics()`. Still pin-pointing what might have caused the error.

> -[NSNull compare:options:range:]: unrecognized selector sent to instance 0x36795e48
> 2016-04-25 23:14:19.209 myApp[202:7262] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[NSNull compare:options:range:]: unrecognized selector sent to instance 0x36795e48

Environment: Xcode (v7.1), iPhone 4S, iOS 9.1

**Comment by tfmontague** [comment]
Looks like `bluetoothle.characteristics` is throwing the error.

**Comment by tfmontague** [comment]
Found the issue. Passed an undefined UUID for the characteristic.

var params = {
  address: "5163F1E0-5341-AF9B-9F67-613E15EC83F7",
  service: "1234",
  characteristics: [undefined]
};
bluetoothle.characteristics(..., params);

**Comment by tfmontague** [comment]
For app stability could implement a schema on the parameters being passed through bluetoothle.js.
https://github.com/molnarg/js-schema

**Comment by randdusing** [comment]
I'll see if the error can be caught within the plugin itself. It shouldn't be left uncaught.

**Comment by randdusing** [comment]
Latest commit in master branch will now check for invalid UUIDs better

**Comment by tfmontague** [comment]
There's still a lot of errors I can throw in your function calls
- Not including parameters
- Including parameters but with the wrong key names
- Including parameters with with the wrong value types (string, number, undefined, null)

It's much more effective to implement a schema at the javascript layer (bluetoothle.js) to catch malformed parameters. Handling malformed parameters at the iOS native layer is not a scalable solution. For every new platform you add, you'll need to write code to handle the parameters. That violates DRY (Don't Repeat Yourself) methodology, and it increases the size of the plugin.

**Comment by randdusing** [comment]
PRs are welcome. Right now I'm more focused on bug fixes and improved BLE functionality coverage since my time is limited.
