### ISSUE TITLE
Restore isNotification param to override default detection on Android

### ISSUE THREAD

**Issue by hanthomas** [randdusing/cordova-plugin-bluetoothle#279]
The characteristic my app is subscribing to is being incorrectly detected as *indicate*.  However, it only works as *notify*.  In previous versions, subscribe() method allowed setting isNotification parameter.  Now that this parameter no longer exists, my app doesn't receive any notifications.  Could the plugin be modified to override the detected subscription type if isNotification parameter exists?

**Comment by hanthomas** [comment]
My bad... didn't realize that the automatic detection was not part of 4.0 release.  Sorry for the false alarm.

**Comment by randdusing** [comment]
No worries, let me know if you find any other issues.
