### ISSUE TITLE
iOS - Read is sent 4 responses!

### ISSUE THREAD

**Issue by tfmontague** [randdusing/cordova-plugin-bluetoothle#282]

**Comment by tfmontague** [comment]
Tested this with `subscribe` and `notify` as well. Get the same behavior.

**Comment by randdusing** [comment]
What's the other device running? Does the error message happen at a certain string length, or all the time?

**Comment by tfmontague** [comment]
_What's the other device running?_
iOS 8, iPhone 4S

_Does the error message happen at a certain string length, or all the time?_
There's no error message. The data is sent 4 times when the value is over 157 bytes.
