### ISSUE TITLE
bluetoothle not found error

### ISSUE THREAD

**Issue by ka347** [randdusing/cordova-plugin-bluetoothle#296]
hey,i am new to hybrid app development. i am using this plugin in telerik platform when i am calling bluetoothle.initialize(). i am getting bluetoothle not found error at the time of debug, 
can please tell me where this is going wrong

**Comment by randdusing** [comment]
Are you calling it before the deviceready event has fired?

**Comment by ka347** [comment]
no

**Comment by randdusing** [comment]
Post the relevant code and I'll see if I can figure out the issue

**Comment by ka347** [comment]
i am new to this and when user clicks myfun2() will be called 
 var params = {
        "request": true,
        "statusReceiver": false,
        "restoreKey": "bluetoothleplugin"
    }
    bluetoothle.initialize(function (result) {
        alert("heyy");
    }, [params]);

**Comment by randdusing** [comment]
That looks fine, but when is the code fired?

**Comment by ka347** [comment]
when click on the button scan for ble the code gets executed

**Comment by randdusing** [comment]
If you can post all your code, that would help a lot.

**Comment by ka347** [comment]
hey i uninsatlled and reinstalled its working, but now when i scan i am getting error as scannning already in progress

**Comment by randdusing** [comment]
I can't really offer much help without taking a look at the code.
