### ISSUE TITLE
startAdvertising: Too large data error

### ISSUE THREAD

**Issue by cjzamora** [randdusing/cordova-plugin-bluetoothle#297]
The startAdvertising returns "Too large data" error, i just figure out that the error occurs when the bluetooth device name on my phone is too long. Is there any way to avoid this problem?

**Comment by randdusing** [comment]
Not that I know of, there's only so much space...

**Comment by RafaelKr** [comment]
If anyone else encounters this issue:
You can pass `includeDeviceName: false` to `startAdvertising`. This worked for me.

Example:
```
var params = {
  "services": ["1234"], //iOS
  "service": "1234", //Android
  "name": "Your long device name",
  "includeDeviceName": false,
};
```
