### ISSUE TITLE
[Question] Two ways communication between devices (Android and/or iOS)

### ISSUE THREAD

**Issue by oktau** [randdusing/cordova-plugin-bluetoothle#308]
Hello,

First of all, thank you for the work done on this plugin.
Can you tell me if is it possible to establish a two ways communication (Android/Android, iOS/iOS or Android/iOS) with this plugin? If yes, is there an example available?

Thank you for your answers.

Best regards.

**Comment by randdusing** [comment]
The Angular wrapper has an example of one way communication that you can check out and then reverse. I don't remember if I tried two way communication while testing, but I think it should work.

**Comment by oktau** [comment]
Hello,

Thank you for your answers. I have done a test with the angular example. Indeed, the two ways communication seems to work properly.

Thanks again.
