### ISSUE TITLE
No Popup on initialize()

### ISSUE THREAD

**Issue by LucasChapuis** [randdusing/cordova-plugin-bluetoothle#312]
I've got this 

<pre> new Promise(function (resolve, reject) {

            bluetoothle.initialize(resolve, reject,
                { request: true, statusReceiver: false });

        }).then(initializeSuccess, handleError); </pre>

Is that normal to not have any prompt to ask to turn on bluetooth while the **request** attribute is set to *true* when the Bluetooth is disabled ?

Thanks in advance !

**Comment by vladimir-kotikov** [comment]
The sample is incorrect - `initialize` method does not accept error callback. This
```js
bluetoothle.initialize(resolve, { request: true, statusReceiver: false });
```
should work.

**Comment by randdusing** [comment]
Thanks @vladimir-kotikov ```initialize()```has gone through some changes and the documentation has been out of sync. @LucasChapuis If this doesn't resolve your issue, please reopen.
