### ISSUE TITLE
Cancelling a pending connect

### ISSUE THREAD

**Issue by RangerMauve** [randdusing/cordova-plugin-bluetoothle#317]
I have a situation when sometimes devices take a *very* long time to connect to a peripheral. I would like to add some sort of logic for timing out the connect call so that a different device can connect to the peripheral instead (it might have a better signal). Currently there doesn't seem to be anything for doing that. I was wondering if calling `close` would cancel the connect, or alternatively if an API can be added for facilitating this use case.

**Comment by randdusing** [comment]
Calling ```disconnect()``` or ```close()``` will cancel the connection. I usually recommend calling ```close()``` so you don't have to use ```reconnect()```.

**Comment by RangerMauve** [comment]
Perfect. Thanks for the confirmation.

Kind of off topic, but should I also be closing when a device disconnects on its own?

**Comment by randdusing** [comment]
Yep, closing tells your phone/tablet that you're no longer using the 'socket'

**Comment by RangerMauve** [comment]
Cool. I think there was a case where I wasn't doing so when I had connection failures which might have led to some trouble
