### ISSUE TITLE
Seems to not be connected even with success on Connect

### ISSUE THREAD

**Issue by LucasChapuis** [randdusing/cordova-plugin-bluetoothle#319]
Here's the problem, I do connect, i create a new page where I display the name of the device, MAC adress etc ... and I try to make a button to disconnect, so i first use Close(), doesnt work ... then i use Disconnect(); same issue.

It's seems like i'm finally not connected, that would explain why I can't DC, so I got the idea to check thanks to : 

<pre> bluetoothle.isConnected(isConnectedSuccess, isConnectedError, device.address); </pre>
<pre> function isConnectedSuccess(result)
{
    console.debug(result);
}</pre>
<pre>function isConnectedError(result)
{
    console.debug(result);
}  </pre>

and here is the result in isConnectedError(); : 

<pre>result = Object {error: "arguments", message: "Argument object not found"} </pre>

while the argument "device.address" is the MAC adress of the device : "20:73:7A:10:00:61"

I thought that it coulnt find a device at the MAC adress "20:73:7A:10:00:61", but it's stupid because in this case it  would have answerd success but with "isConnected": false

So i've got a valid parameter (at least i think) but it tells me I don't ... need help ><

[See here](http://img4.hostingpics.net/pics/486279Sanstitre.png)

**Comment by randdusing** [comment]
Params should always be an object. So params for connect, disconnect or close may look like below:

```
{
  address: "12:34:56:78:90:AB"
}
```
