### ISSUE TITLE
connect() do not have any callback

### ISSUE THREAD

**Issue by wangxiao** [randdusing/cordova-plugin-bluetoothle#323]
I called `bluetoothle.connect`, but it do not have any callback, is connecting need a very long time (> 10min) ？

My code like this:
```javascript
var connectTimes = 0;
var scan = function() {
  bluetoothle.startScan(function(res) {
    if (res.address && !connectTimes) {
      connect(res.address);
      stopScan();
      connectTimes ++;
    }
  });
};

function stopScan() {
  bluetoothle.stopScan();
}

function connect(address) {
    bluetoothle.connect(function(res) {
        alert('ok');
    }, function(err) {
       alert('T-T');
    }, {
      address: address,
    });
}
```

**Comment by randdusing** [comment]
Hmm, the code looks fine. You're able to see it in the scan results, but trying to connect just times out?

**Comment by wangxiao** [comment]
Thx, the results also look good.
I think i need check the native android java code with my android developer friends.

**Comment by randdusing** [comment]
Try using something like LightBlue to see if you can connect with other apps on the same phone.

**Comment by wangxiao** [comment]
Yes, it is ok. Use the official native android App of the bluetooth device can connect.

**Comment by wangxiao** [comment]
After long time, maybe 10 min, show the connect failed.

**Comment by wangxiao** [comment]
android version 5.1, connect always failed.   https://github.com/randdusing/cordova-plugin-bluetoothle/issues/185

**Comment by hazemhagrass** [comment]
Any updates here!

**Comment by randdusing** [comment]
@hazemhagrass I need more details!

**Comment by hazemhagrass** [comment]
Here is a sample of my code:
`$cordovaBluetoothLE.initialize({request: true}).then(null, function (obj) {
                console.log("INITIATE BLUETOOTHLE ERROR : " + JSON.stringify(obj));
            }, function (obj) {
                console.log("INITIATE BLUETOOTHLE SUCCESS : " + JSON.stringify(obj));

                function onBondCallback(obj) {
                    if (obj.status !== 'bonded') {
                        return;
                    }
                    console.log("BONDING BLUETOOTHLE : " + JSON.stringify(obj));
                    isLocationEnabled(function () {
                        console.log("START BLUETOOTHLE CONNECTION TO DEVICE: " + $scope.hrm.address);
                        $cordovaBluetoothLE.connect({
                            address: $scope.hrm.address,
                            autoConnect: true
                        }).then(null, function (obj) {
                            console.log("BLUETOOTHLE CONNECTION ERROR : " + JSON.stringify(obj));
                        }, function (obj) {
                            console.log("BLUETOOTHLE CONNECTION SUCCESS : " + JSON.stringify(obj));
                            if (obj.status == 'connected') {
                            } else if (obj.status == 'disconnecting' || obj.status == 'disconnected') {
                            }
                        });
                    });
                }

                function onUnbondingCallback(obj) {
                    console.log("UNBONDING BLUETOOTHLE : " + JSON.stringify(obj));
                    $cordovaBluetoothLE.bond({address: $scope.hrm.address}).then(null, onBondCallback, onBondCallback);
                }

                if (ionic.Platform.isAndroid()) {
                    $cordovaBluetoothLE.unbond({address: $scope.hrm.address}).then(onUnbondingCallback, onUnbondingCallback);
                }
                else {
                    onBondCallback({status: 'bonded'});
                }

            });`

**Comment by hazemhagrass** [comment]
@wangxiao did you solve your problem? seems that I have an issue just like you

**Comment by randdusing** [comment]
@hazemhagrass Details besides the code as well, what device, version, etc?

**Comment by wangxiao** [comment]
@hazemhagrass  sorry, i have not solve the problem. Now i have developed Android native app, and found a Android engineer.
