### ISSUE TITLE
ios asks to turn on bluetooth every time the app is started if bluetooth is off

### ISSUE THREAD

**Issue by FutoRicky** [randdusing/cordova-plugin-bluetoothle#325]
Everytime the app is started it asks to turn on bluetooth (which is annoying) is the bluetooth is off on the device. Is there any way to avoid this?

**Comment by randdusing** [comment]
Set ```request: false``` in the ``ìnitialize()``` call: https://github.com/randdusing/cordova-plugin-bluetoothle#initialize

**Comment by FutoRicky** [comment]
Missed that, sorry. Thanks!
