### ISSUE TITLE
what happens to app when a read request receive?

### ISSUE THREAD

**Issue by mjseyyedi** [randdusing/cordova-plugin-bluetoothle#328]
how can I understand a read request happened and I should call my read function??
is there any event for that?

**Comment by randdusing** [comment]
Yep, check out the documentation here for the different event types: https://github.com/randdusing/cordova-plugin-bluetoothle#initializeperipheral

**Comment by mjseyyedi** [comment]
could you please give me an example?? I think I can't follow your descriptions. I'm totally idiot :(
