### ISSUE TITLE
Android : writeAction work success ,but return null Object ,when i use Version 3.0

### ISSUE THREAD

**Issue by htyi** [randdusing/cordova-plugin-bluetoothle#332]
version  is 3.0 .   when i use writeAction ,it  work well.  but  what it  return to me is NULL.   please give some directions?    what i  want to  do is  when i send an order to peripheral, it return the result to  me .

**Comment by randdusing** [comment]
What's returning null? Can you provide your write related functions?

**Comment by randdusing** [comment]
Please re-open if you can recreate this on the current version.
