### ISSUE TITLE
steps of receiving data

### ISSUE THREAD

**Issue by mjseyyedi** [randdusing/cordova-plugin-bluetoothle#334]
I'm totally new to BLE , could you please give me steps of receiving data . I mean what functions should I call and in what order to get the value of sent data from bluetooth device?

should I use notify?? I used it and passed the params which you said in doc , first I had device address not found error , then I added it , but now I got error of service not found. service which I'm passing is returned one from discover function!

**Comment by randdusing** [comment]
The [readme](https://github.com/randdusing/cordova-plugin-bluetoothle#central-life-cycle) shows the high level steps for connecting and reading to the device. Also, check out the ionic based example in the [angular wrapper](https://github.com/randdusing/ng-cordova-bluetoothle).

**Comment by mjseyyedi** [comment]
I've read all these docs before, but I explain the problem to you , maybe you could help me.
I can connect and write successfully to my ble board. but when I send data from board to my phone , no event in initializePripheral Callback triggers! but when I use nordicsemi's official android app , I receive it. I don't know what I'm missing. should I subscribe to any service for receiving data or what??

**Comment by randdusing** [comment]
initializePeripheral is only if your app is acting as a peripheral. Is you app supposed to be a peripheral or central?

**Comment by mjseyyedi** [comment]
I think it's central. What other way is for central app

**Comment by mjseyyedi** [comment]
I mean how can I read data, in my central device?

**Comment by randdusing** [comment]
I can't really provide one on one help unfortunately. Please checkout the readme and the example. If you have any specific questions, please post the relevant code.
