### ISSUE TITLE
Can't get result from subscribe

### ISSUE THREAD

**Issue by LucasChapuis** [randdusing/cordova-plugin-bluetoothle#341]
Hi,

I initialize, connect, discover, subscribe

So i've got this at the end : 

<pre>
function subscribe(address)
{
    new Promise(function (resolve, reject) {
        bluetoothle.subscribe(resolve, reject, { 
            "address": address,
            "service": inemotion.GYROSCOPE_SERVICE,
            "characteristic": inemotion.GYROSCOPE_DATA,
        });
    }).then(subscribeSuccess, handleError);
}

function subscribeSuccess(result)
{
    if(result.status == "subscribed")
    {
        console.log("Subscription has started.");
    }
    else if(result.status == "subscribedResult")
    {
        var gyroscopeValueBytes = bluetoothle.encodedStringToBytes(result.value);
        var gyroscopeValueString = bluetoothle.bytesToString(gyroscopeValueBytes);

        document.getElementById("gyroscopeValue").innerHTML = gyroscopeValueString;
    }
}
</pre>

I get in the <pre> if(result.status == "subscribed") </pre>

after I connect so I guess subscription has succeeded, but when I move the device with the gyroscope, I never get in the <pre> else if(result.status == "subscribedResult") </pre> like nothing is happening, I don't know if i'm using your code right ...

**Comment by randdusing** [comment]
The subscribe call shouldn't be wrapped in a promise since that's only going to allow successCallback to be called once.
