### ISSUE TITLE
Android: Discover method returning exception.

### ISSUE THREAD

**Issue by DaniloCouto** [randdusing/cordova-plugin-bluetoothle#342]
After a succeeded connection with an Bluetoothle device, I tried to discover his services and characteristics.
But, sometimes , the method returns an Java Exception : 
`Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference`

It seems that the wasNeverConnected Native Java method is returning Null without throwing an callback. and during the discoverAction Method  it's impossible to convert a null object to string.

Edit: 

I just found this error on android 5.1 and 6.0.
So it seems an general error, i'll look foward to test this error on iOS too.

**Comment by randdusing** [comment]
Do you know what line it's throwing the error?

**Comment by DaniloCouto** [comment]
On 1615 line of BluetoothLePlugin.java
I've even put a log to see if the `connection.get(keyDiscoveredState)` was really null on .toString.
`Log.v("MyBlueTest", "connection = " + connection.get(keyDiscoveredState));`
And yes, the log returned null.

But this error is odd and happen hardly ever.
And after that error if I try to restart the bluetooth by turning on and off, the bluetooth just... dies, and I need to restart the phone.

**Comment by hannibaldinski** [comment]
Not sure but this might be related.

When I try connecting and it fails. The second time I try to connect and it succeeds, the discover function will return NULL in its error callback. I can fix it by calling close() and then connect() again.

![error](https://cloud.githubusercontent.com/assets/3531514/18365299/77f41ef0-7612-11e6-8aa3-5e46af46bb42.png)

**Comment by randdusing** [comment]
You shouldn't be able to call connect back to back. Are you calling close in between? Or are some of those actually reconnect calls? If that's reconnect, I think I know the issue and will fix it this evening!

**Comment by randdusing** [comment]
Actually just committed the change with master, I'm curious if you can still recreate.

**Comment by randdusing** [comment]
Please re-open if that doesn't fix it
