### ISSUE TITLE
Pairing iOS on a slave device with security request

### ISSUE THREAD

**Issue by DaniloCouto** [randdusing/cordova-plugin-bluetoothle#346]
I have a custom slave device that after connection emit a security request.
There's any kind of procedure on iOS to emit a similar dialog like bond on Android?

Edit: 
Ok, I did get a little more deep on this subject.
I've found these Guide Lines By Apple : https://developer.apple.com/hardwaredrivers/BluetoothDesignGuidelines.pdf

>  If, for security reasons, the accessory requires a bonded relationship with the Central, the Peripheral should reject the ATT request using the Insufficient Authentication error code, as appropriate. As a result, the Apple product may proceed with the necessary security procedures.

As this rule follows, what should be the plugin behavior about an Insufficient Authentication error code on a discover method? Is it even possible?

**Comment by randdusing** [comment]
iOS should automatically start the pairing request once it receives the Insufficient Authentication error code. It's been a while since I worked with a paired device, but nothing special had to be done on the iOS side if I remember correctly.

**Comment by DaniloCouto** [comment]
Thanks for answering.
I'll look forward if it's something wrong with the custom slave device. 
Consider this "Issue"/Question closed. 
close #346
