### ISSUE TITLE
Read current MTU Size

### ISSUE THREAD

**Issue by jpatel88** [randdusing/cordova-plugin-bluetoothle#354]
Is there any way to read current MTU size in Android and iOS? I have a BLE Peripheral device which tries to renegotiate the MTU Size to 512 bytes, but that works for Android, but iOS maxes out at 158 bytes. On the mobile application, I don't want to hardcode the MTU sizes as per OS - so am looking for means to read the current MTU size. I need to send commands to the BLE peripheral as per the current MTU Size.

**Comment by randdusing** [comment]
On Android, looking at the source there isn't a way to read the current MTU without actually calling requestMtu(). On iOS, there isn't anything available in the API. I believe iOS hides this on purpose.
