### ISSUE TITLE
iOS Notification does not notify what it should after disconnection

### ISSUE THREAD

**Issue by Dagrut** [randdusing/cordova-plugin-bluetoothle#363]
Hi!

First of all, thank you for this great plugin! The center side work well 😄 

On the peripheral side, I have a problem : When I start to advertise using my parameters, everything works. However, if a center connects on it and then disconnects, the advertised data are not the same : 
The name changes to "iPad" or "iPhone" (depending on which device is advertising) and the number of services is 0 (according to the lightblue app).
If I wait long enough (something like 5 or 10 minutes), it may come back to a normal state again.

What I'm doing on the peripheral side is : 
- .initialize() (Returns OK)
- .initializePeripheral (Returns OK/enabled)
- .addService (with one service and one characteristic, returns OK)
- .startAdvertising (using these same parameters, returns OK)

When a device connects or disconnects, I don't get the "connected" or "disconnected" state in the initializePeripheral callback, I directly get "subscribed" or "unsubscribed" (and by the way, not "subscribedToCharacteristic" or "unsubscribedToCharacteristic" as said in the documentation).

Also I tried to stop the notifications when a device connects and start it again when it disconnects, this does not solve the problem.

I'm working with an iPhone 5s using iOS 10.0.2 and an iPad Mini using iOS 9.3.5.

As a side note when I connect from lightblue, it asks me to peer devices like normal bluetooth or so, which seems weird to me...

Edit: I forgot to add that I'm using Meteor 1.4.1 and the plugin version I use is 4.3.0.

Edit 2: If I don't filter by bluetooth device name, everything works, so this is not a real bug for me anymore, but still, it seems odd :-) .

**Comment by randdusing** [comment]
Updated that documentation for the subscribed/unsubscribed documentation. I also added a note about iOS changing the name to the name of the device like Rand's iPhone. I've noticed that in the past, but had never documented it. I'm not sure of a way around it.

The best way around all of this is to just do the filtering by UUID. Filtering by name is less performant and prone to issues like this.

If you can recreate the zero services issue, please re-open!
