### ISSUE TITLE
Android 6.0 automatically open paring popup on bond

### ISSUE THREAD

**Issue by DaniloCouto** [randdusing/cordova-plugin-bluetoothle#364]
On Android 6.0 , during an bonding request, the android 6.0 natural behavior is to send an local notification to open the paring PopUp for PIN insert.
It is possible to open this PIN insert PopUp automatically without the notification?

**Comment by randdusing** [comment]
I don't see any options available in the API. But I want to say this behavior varies between devices. If I recall correctly, my Samsung Galaxy Tab had a slightly different pairing process that my Nexus tablet and phone. Still probably not customizable either way.

**Comment by DaniloCouto** [comment]
Thank You @randdusing 
Consider this #364 close
