### ISSUE TITLE
What is the requirement of this plug-in to the Bluetooth module

### ISSUE THREAD

**Issue by zhuqingsong59** [randdusing/cordova-plugin-bluetoothle#372]
What is the requirement of this plug-in to the Bluetooth module, as long as it is 4.0 and above, I made a app, but in different Android mobile phone, the effect is different, one normal, one can not scan my Bluetooth module ,they all are Android 4.3 or higher

**Comment by phy25** [comment]
Bluetooth Low-Energy (BLE) is only available since "Bluetooth 4.0+". Some phones may not support this.

**Comment by randdusing** [comment]
Are you saying one device doesn't pick up another? The app will only pick up devices that are actively advertising as BLE devices. Most phones will not advertise as BLE devices unless another app is telling them to do so.

**Comment by zhuqingsong59** [comment]
thanks for help
