### ISSUE TITLE
bluetoothle.writefunction has error: Service not found

### ISSUE THREAD

**Issue by Aaronwong94** [randdusing/cordova-plugin-bluetoothle#378]
I'm using bluetoothle.write(). the {para} i had hardcode with the service uuid and charcteristic uuid (since I know the service uuid and charcteristic uuid) however the error i obtain said the Service not found. Please help!!

**Comment by Huiting-Yeong** [comment]
Had a similar error when trying to subscribe to a service. I solved it by running bluetoothle.discover() first then subscribing. You can try discovering first then write.

**Comment by randdusing** [comment]
Yep, you need to discover prior to using any actions

**Comment by Aaronwong94** [comment]
I had try using bluetoothle.discover(). I can get the device.adress, but can't get the serviceuuid and characteristicuuid, how should i retrieve that ?As what i get device.services are an object array,

**Comment by randdusing** [comment]
You need to parse the object if you want to iterate through the services and characteristics. The format is documented in the readme. But you don't necessarily need to do that, just discover and then call read/write/etc

**Comment by Aaronwong94** [comment]
Sorry I don't quit get it Cus when I dicover how can I retrieve the service uuid and characteristics uuid Cus what I get is a object array. What should I do to get the uuid for read and write function {param}

Sent from my iPhone

On 10 Nov 2016, at 5:57 PM, Huiting-Yeong <notifications@github.com<mailto:notifications@github.com>> wrote:


Had a similar error when trying to subscribe to a service. I solved it by running bluetoothle.discover() first then subscribing. You can try discovering first then write.

-

**Comment by randdusing** [comment]
Take another look at the documentation and check out the Angular wrapper provided in the example if needed.

**Comment by akashkhairnar01** [comment]
where is angular wrapper provided example

**Comment by randdusing** [comment]
https://github.com/randdusing/ng-cordova-bluetoothle
