### ISSUE TITLE
bluetoothle.write : Unable to write on return

### ISSUE THREAD

**Issue by Huiting-Yeong** [randdusing/cordova-plugin-bluetoothle#379]
Hi

I am trying to write a value to the ble object. I am successful in initialize, startScan, connect, discover and subscribe. 

When I run bluetoothle.write(), I am getting an error: **Unable to write on return**

```
var string = "write value";
var bytes = bluetoothle.stringToBytes(string);
var encodedString = bluetoothle.bytesToEncodedString(bytes);

new Promise(function (resolve, reject) {

  bluetoothle.write(resolve, reject, { "address" : zoneA.macAddress, "service" : "ffe5", "characteristic" : "ffe9", "value" : encodedString});

}).then(writeSuccess, handleError);

function writeSuccess(result){
  console.log(result);
}

function handleError(error){
  console.log(error);
}

```

Error:

> address: "..."characteristic: "FFE9"error: "write"message: "Unable to write on return"name: "..."service: "FFE5"

Any idea on what I am doing wrong?

**Comment by randdusing** [comment]
That looks fine to me. Can you list out the properties for that service that are in the discover call?

**Comment by Huiting-Yeong** [comment]
![image](https://cloud.githubusercontent.com/assets/20330259/20201166/eaa0f558-a7f0-11e6-9b41-d3793e9a6e1d.png)

This is the list of properties I am getting

**Comment by Huiting-Yeong** [comment]
Did some debugging in the java file and realised in `onCharacteristicWrite(...)`, the status value is equal to 133 (BluetoothGatt.GATT_ERROR). Any idea how does that come about?

**Comment by randdusing** [comment]
Can you get the system level Bluetooth HCI logs or some higher level BLE logs from Android Device Monitor? And what type of phone is this on?

**Comment by Huiting-Yeong** [comment]
Yes, I am able to get Bluetooth HCI logs and have tried opening them with wireshark. But I am not sure how to interpret them. I am running it on Android 5.0.

**Comment by Huiting-Yeong** [comment]
Hi, it is suddenly returning me a status of 0, even though I didn't change any code. Not sure why but thanks so much for all your help!

**Comment by randdusing** [comment]
No worries. Maybe a fluke on the phone or device side, but glad it's working now.

**Comment by Funkelfetisch** [comment]
I'm having the same problem (I think)

**Comment by ZweiEuro** [comment]
I am having the same issue

**Comment by clarklight** [comment]
I am having the same problem as well. when i do .read() it says unable to read, when i do write() it says Unable to write on return, i am using another android phone and setting it as a peripheral.
