### ISSUE TITLE
Popup request pair need discover device, how without connect first?

### ISSUE THREAD

**Issue by estvmachine** [randdusing/cordova-plugin-bluetoothle#382]
Hi im searching how make always appear the popup of request pair bluetooth, for that i need: 

(http://stackoverflow.com/questions/26143680/bring-bluetooth-pairing-dialogue-to-the-front)
1. If the device was in discoverable mode recently
2. If the device was discovering recently
3. If the device was picked in the device picker recently
4. If Bluetooth Settings is visible

But when i use the bluetoothle.discover(), say i need to connect first. So how can i do this : discover and bond, then connect or whatever one want?

**Comment by randdusing** [comment]
```startDiscovery()``` is unrelated to this plugin's ```discover()```. ```discover()``` is used to discover the BLE device's services and characteristics. If you want to the prompt the bonding popup/notification (depends on version and vendor), use ```bond()```. ```connect()``` and ```discover()``` can wait until after bonding.

**Comment by estvmachine** [comment]
The problem with bond(), its internally exist a logic between show the popup for request bluetooth or show a notification. What i really need is always show the popup.  You know how i can do that?, this plugin which version of android can assure that behavior?

**Comment by randdusing** [comment]
Yah, I don't think that's possible based on what I see in the API.

**Comment by estvmachine** [comment]
Ok,  thanks with this plugin we cant assure that behavior.
