### ISSUE TITLE
Is there any way to know on which mac address the peripheral will advertise (Peripheral Mode)?

### ISSUE THREAD

**Issue by rajatsawant** [randdusing/cordova-plugin-bluetoothle#394]
I want a hm 10(hardware) ble module to connect to my peripheral app using the mac address on which my app advertises. But unfortunately I am unable to know the random mac address that gets generated everytime i start advertising. Is there any way to know the random mac address through this plugin or by any other means?

**Comment by randdusing** [comment]
On Android, yes since the MAC address is the address used. On iOS, not possible.
