### ISSUE TITLE
README observation

### ISSUE THREAD

**Issue by sunny-mittal** [randdusing/cordova-plugin-bluetoothle#399]
This isn't a huge deal, but I thought it was worth mentioning that your `isBonded` documentation specifies Android-only, as it should, but shows an example with an iOS-style address. I didn't wanna fork the repo just to issue a PR for that so mentioned it here :)

**Comment by sunny-mittal** [comment]
Oh, never mind...Just realized that the same address example is used throughout.

**Comment by randdusing** [comment]
Thanks, I fixed that in the documentation.
