### ISSUE TITLE
Request: Please add a time limit parameter in connect() and reconnect()...

### ISSUE THREAD

**Issue by rajatsawant** [randdusing/cordova-plugin-bluetoothle#400]

**Comment by randdusing** [comment]
This is fairly easy to add at the Javascript level, which is what I do with the Angular wrapper. I don't plan to add this at the plugin level since it's unnecessary in my opinion and a lot of plugin level coding.

**Comment by rajatsawant** [comment]
Thanks for the reply, I just wanted to know for how long should I try to connect before disconnecting? How many seconds? P.S. The BLE peripheral would be within range whenever I try.

**Comment by randdusing** [comment]
For my app I did about 10 seconds on iOS and 15 on Android. You really need to play around with your BLE device and a variety of phones to see what works best.

**Comment by rajatsawant** [comment]
Thanks.
