### ISSUE TITLE
iOS background scanning

### ISSUE THREAD

**Issue by graphicgeek** [randdusing/cordova-plugin-bluetoothle#41]
Does scanning fully work in the background in iOS?

I've added the phonegap background plugin (https://github.com/hazemhagrass/phonegap-background), and Bluetooh is scanning in the background, but it does not get any results. I get results when I have the app open, just not when it is in the background. 

The console shows the scanStart is succeeding when running in the background, just not getting results. Any thoughts?

FYI, I'm testing on an iPad Mini.

**Comment by De-Lac** [comment]
Hello. I've just tried your proposed solution, a cycle of start&stop, anyway when I exit the app, the scan stops immediately.  Should I use any other plugin for the background? Did you manage to make it work?
Thanks

**Comment by randdusing** [comment]
@De-Lac Is this for iOS, Android or both?

**Comment by De-Lac** [comment]
I am using IOS, but I'd like to have a solution for both :)

**Comment by De-Lac** [comment]
Actually with the plugin `de.appplant.cordova.plugin.background-mode` the cycle continuos also in background, but the scan is no performed.

````javascript
var _startCycle = function()
{
 console.log('start cycle');
 bluetoothle.startScan(_successCallback, errorCallback, {allowDuplicates: true});
 _startCycleRouting = setTimeout(function(){_stopCycle();}, 8000);	
}

var _stopCycle = function()
 {
   console.log('stop cycle');
  bluetoothle.stopScan(_successCallback, errorCallback} );
    _stopCycleRouting = setTimeout(function(){_startCycle();}, 1000);	
  }	
````

console
````
2015-10-21 15:45:14.175 eppoiBeacon[4279:907472] START SCAN !!!
2015-10-21 15:45:18.134 eppoiBeacon[4279:907472] PAUSE -> BACKGROUND !!!
2015-10-21 15:45:22.198 eppoiBeacon[4279:907472] stop cycle
2015-10-21 15:45:22.201 eppoiBeacon[4279:907472] STOP SCAN !!!
2015-10-21 15:45:23.198 eppoiBeacon[4279:907472] start cycle
2015-10-21 15:45:23.198 eppoiBeacon[4279:907472] START SCAN !!!
2015-10-21 15:45:31.210 eppoiBeacon[4279:907472] stop cycle
2015-10-21 15:45:31.213 eppoiBeacon[4279:907472] STOP SCAN !!!
2015-10-21 15:45:32.212 eppoiBeacon[4279:907472] start cycle
2015-10-21 15:45:32.213 eppoiBeacon[4279:907472] START SCAN !!!
````

**Comment by randdusing** [comment]
@De-Lac How long is your scan lasting for? After rereading Apple's documentation, a short scan may not pick up all the devices since it's waiting to coalesce all the advertisements into a single advertisement. That would kind of explain why I sometimes found my heart rate monitor and sometimes didn't with a scan interval of 10 seconds. Maybe increasing this to 20 seconds would have had better results.

```
Although you can perform many Bluetooth-related tasks while your app is in the background, keep in mind that scanning for peripherals while your app is in the background operates differently than when your app is in the foreground. In particular, when your app is scanning for device while in the background:

The CBCentralManagerScanOptionAllowDuplicatesKey scan option key is ignored, and multiple discoveries of an advertising peripheral are coalesced into a single discovery event.
If all apps that are scanning for peripherals are in the background, the interval at which your central device scans for advertising packets increases. As a result, it may take longer to discover an advertising peripheral.
These changes help minimize radio usage and improve the battery life on your iOS device.
```

**Comment by De-Lac** [comment]
As the example code I posted, I stop the cycle after 8000ms.  I've just tried now with 20s and more... but  nothing happens :(     start and stop cycle, but no scan performed

**Comment by randdusing** [comment]
@De-Lac What type of device are you using specifically? It may vary between iPad and iPhone models

**Comment by De-Lac** [comment]
iPhone 6

**Comment by ogyasmin** [comment]
Hi Randding is this bug fixed ?
My ios app doesn't found anything in background but the scanning is running ?
When the app is in foreground the discovery going well but in background nothing was discovered .
Do you have an idea?

**Comment by ogyasmin** [comment]
Tested with:
iPhone 6
iPhone 6 +
iPhone 5

**Comment by randdusing** [comment]
@ogyasmin iOS limits background scanning. You can see the excerpt in some of my posts above. How long are you scanning for in the background?

**Comment by ogyasmin** [comment]
As long as the user put the application in background.

**Comment by randdusing** [comment]
So how long is that during testing?

**Comment by ogyasmin** [comment]
In background my loop is scanning 2 seconds sleep 10 seconds.

var _startCycle = function()
{
 console.log('start cycle');
 bluetoothle.startScan(_successCallback, errorCallback, {allowDuplicates: true});
 _startCycleRouting = setTimeout(function(){_stopCycle();}, 2000);  
}

var _stopCycle = function()
 {
   console.log('stop cycle');
  bluetoothle.stopScan(_successCallback, errorCallback} );
    _stopCycleRouting = setTimeout(function(){_startCycle();}, 10000);   
  }

**Comment by ogyasmin** [comment]
My test during 1 mintes

**Comment by randdusing** [comment]
Check out the documentation: https://developer.apple.com/library/mac/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/CoreBluetoothBackgroundProcessingForIOSApps/PerformingTasksWhileYourAppIsInTheBackground.html

2 seconds is most likely not enough time

**Comment by ogyasmin** [comment]
thanks I will read the documentation and tell U if it's work

**Comment by andySigler** [comment]
I'm having the same issue. I have an infinite loop, where every 20 seconds I 'stopScan' then 'startScan'. I pickup many advertisements while in foreground, but zero when in background. I know the background functions are working because I am successfully executing HTTP requests while in background. The plugin is throwing no errors. Other than the default setup, I have also tried setting 'allowDuplicates' to true and false, but neither return scan results while in background. Foreground works as expected.

I'm on iOS 8.3 and Cordova 5.2

Any help on this would be great, my application could really use this :)

**Comment by randdusing** [comment]
@andySigler If you set it to something higher like 1 minute, does anything appear?

**Comment by andySigler** [comment]
I spoke too soon! I was improperly setting the serviceUUID filtering when calling 'startScan'. So now it works with the falling options being passed to 'startScan':

```
var options = {
        'serviceUuids':['2220'],
        'allowDuplicates' : true
}
```

where '2220' is the name of a service on my peripheral.

For anyone else trying to do this, this was done in combination with [this plugin for background processes](https://github.com/katzer/cordova-plugin-background-mode), installing with `--noregistry ` as told in [this comment](https://github.com/katzer/cordova-plugin-background-mode/issues/86#issuecomment-162167491). I've spent all day hobbling this together, glad to see it finally working :D

**Comment by randdusing** [comment]
Ahh, glad you got it working!

**Comment by randdusing** [comment]
Anyone still having issues with? I looked into this recently and have a few notes to help recap:

- Background scanning is slower.
- Background scanning must filter by a service.
- If the app falls asleep while scanning, it will awaken on a scan result. It will fall asleep after 10 seconds maximum.
- Keep background scan on instead of toggling on and off.
- Notice the warning on background mode plugin. Apple reviewers may ask why you're using background audio mode.
