### ISSUE TITLE
How to solve ios writing is not permitted ？？

### ISSUE THREAD

**Issue by jimmyYSY** [randdusing/cordova-plugin-bluetoothle#412]
i have a app for ios , but when i use bluetoothle ,it's tell me ' ios writing is not permitted '. how to solve ;
please everyone. thanks everyboby.

**Comment by randdusing** [comment]
What are the properties of that characteristic?

**Comment by jimmyYSY** [comment]
Thank you very much ,i have solved the problem.i added this code
                     'if(isiOS){
                        params.type = 'noResponse'
                    }'
