### ISSUE TITLE
isEnabled false before initialization

### ISSUE THREAD

**Issue by sunny-mittal** [randdusing/cordova-plugin-bluetoothle#414]
Many (most) methods return "bluetooth not initialized" or equivalent if called before `initialize`, but `isEnabled` returns false until initialization occurs, making it hard to make conditional decisions based on the bluetooth radio state. Now I don't know enough about this level vis a vis app development, so is this a limitation of the OS or something that can be changed/modified in the plugin? Thanks!

**Comment by randdusing** [comment]
You need to call bluetoothle.initialize() before anything else

**Comment by sunny-mittal** [comment]
In that case, shouldn't it return the same error as other calls (i.e. Bluetooth not initialized) rather than `false`? I think it'd be more consistent and less confusing :D Thanks for the quick response, though!

**Comment by randdusing** [comment]
Oh I misread your comment. Yah perhaps isEnabled and isScanning should return an error, but true/false is simpler to handle.

**Comment by sunny-mittal** [comment]
That's fair. I'm closing this issue as resolved. Hopefully someone else will benefit from it and thanks again for the explanation!
