### ISSUE TITLE
background on ios (Terminated due to signal 9)

### ISSUE THREAD

**Issue by fjlogrono** [randdusing/cordova-plugin-bluetoothle#420]
First, thank you very much for the plugin.
I have a problem, I've been trying to do something and I do not know how to solve it.
I need to get the heart rate, and if it is less than or greater than a range of values, send an alert using pushplugin.

When it enters the background, it only works correctly 30 seconds. Then the app closes. How can I continue to obtain the heart rate with the subscribed method and continue to send alerts if it goes out of range?

If I have bluetooth-central in the config.xml, should not be in the background running the subscribed method without stopping?

In the initilized method, I also have the restorekey.

I'm using ng-cordova-bluetooth for angulajs, and the Central Life Cycle.

I'm starting to think that there is a cpu problem, and the app is closed. 

THREAD WARNING: ['BluetoothLePlugin'] took '18.434082' ms. Plugin should use a background thread.

I receive the data correctly when it is in the foreground (bluetoothle.subscribe (subscribeSuccess, subscribeError, params);), but when I send it to the background, after a few seconds the application closes:

Terminated due to signal 9

This happens to me in iOS 10 on an iphone 5s.
In android also closes after a few hours.
It may be time scanning in the background, but instead when subscribed, after a while the app closes.

some help?

thank you very much

**Comment by fjlogrono** [comment]
Maybe, the subscribed method is running in the background, and I need to activate the background mode when the heart rate is out of range, send the alert, and send it back to the background. I understand that the subscribed method will continue to process the data.

I'll try that.

Android works perfectly

**Comment by fjlogrono** [comment]
I think the subscribed method is not working in the background, because Ios debugger closes when a few seconds passes in the background. This happens to me even with and without the background mode plugin.

**Comment by fjlogrono** [comment]
I'm starting to think that there is a memory problem, and the app is closed.

**Comment by fjlogrono** [comment]
I left the application in the background and it did not close. 

Then, I have reactivated and received bluetooth data (bluetoothle.subscribe (subscribeSuccess, subscribeError, params);), and after a few seconds the application has been closed when in the background:

Terminated due to signal 9

some help?
Thank you!

**Comment by fjlogrono** [comment]
This happens to me in iOS 10.

**Comment by fjlogrono** [comment]
Seems to be a performance issue for my app, not its plugin. sorry for the inconvenience.

**Comment by randdusing** [comment]
Thanks for the update and hope you figure out the performance issue.
