### ISSUE TITLE
Changed devicename not updated during scanning

### ISSUE THREAD

**Issue by Wieltje** [randdusing/cordova-plugin-bluetoothle#428]
When the advertised device name of a peripheral is changed during scanning, this new name is not available in the scanResult callback. Inspection of the scanResult.advertisement learns me that the new name is actually available.

Proposal for a fix/workaround:
It seems that device.getAddress(), called in addDevice returns the old name (I consider this as a bug), while the new name can be retreived via  result.getScanRecord().getDeviceName().

I've tried to fix this for a PR, but I'm struggling with the string type output of result.getScanRecord().getDeviceName(), so I hope that someone can implement a easy fix for this.

FYI: I'm running on a Galaxy Tab S2 with Android 6.0

**Comment by randdusing** [comment]
PR looks mostly good. What did you mean by struggling with the string output?
