### ISSUE TITLE
Upgrade Nordic device firmware with DFU 

### ISSUE THREAD

**Issue by jiboune** [randdusing/cordova-plugin-bluetoothle#459]
Hi there, thank you for this great plugin. I'm currently receiving data from my device and it works pretty good. I was wondering how to deal with DFU (using Nordic component) in order to upgrade my firmware. Is it possible to do it with this plugin ? 

Another library did it here https://github.com/fxe-gear/cordova-plugin-ble-central and I would like to know if the solution is currently implemented. Thank you

**Comment by randdusing** [comment]
It's possible, but you'll have to write the upgrade logic at the Javascript layer. This plugin just gives access to the Bluetooth API. The linked plugin appears to use a Nordic library to do the actual upgrade work. I have no plans on implementing something that specific in this plugin.
