### ISSUE TITLE
Is it possible to turn off the Bluetooth ?

### ISSUE THREAD

**Issue by Trauck** [randdusing/cordova-plugin-bluetoothle#482]
I use the plugin to connect to a Bluetooth device, it works fine, however I have not found a function to turn off the Bluetooth, not just to disconnect. I use a switch to launch the Bluetooth and I would like that when my switch is off Bluetooth is also.

Thank.

**Comment by randdusing** [comment]
https://github.com/randdusing/cordova-plugin-bluetoothle#disable
