### ISSUE TITLE
Unable to connect on Windows

### ISSUE THREAD

**Issue by MalikDrako** [randdusing/cordova-plugin-bluetoothle#487]
I am able to scan for bluetooth devices, but when I try to connect on Windows, there is a native popup saying "Connecting to <device>" followed by "Connection failed".

Stepping through the plugin JS, the error is logged from BluetoothLePlugin.js#L265, but the DevicePairingResultStatus code is 19: An unknown failure occurred.

My connection code is pretty simple:
```
app.bt_connect = function(address) {
	var params = { address: address };
	bluetoothle.connect(onConnect, onConnectError, params);
}
function onConnectError(result) {
	console.error(result);
}
```

**Comment by MalikDrako** [comment]
It turns out the device I am trying to connect to doesn't support pairing. Newer versions of Windows 10 support communicating without pairing, how would I modify the plugin to allow this?

**Comment by randdusing** [comment]
Not experienced with the windows side of BLE at all...

**Comment by randdusing** [comment]
Please reopen if @TheBosZ 's recent changes didn't fix this.
