### ISSUE TITLE
[question] is there any possibility to discover BLE device without its advertising

### ISSUE THREAD

**Issue by dayxahoi** [randdusing/cordova-plugin-bluetoothle#489]
Appreciate your plugin. 
I am developing application for ios device. Your plugin can discover BLE device only if BLE device advertising (and I think this is essential for BLE, right ?). Is there any possibility to discover BLE device without its advertising at all ? I want to discover all bluetooth devices around. If the answer is NO, then I am curious why iphone native bluetooth can discover other bluetooth phones ?

Regards

**Comment by randdusing** [comment]
This plugin only supports BLE. If you want to discover Bluetooth devices (that aren't advertising as BLE devices), you'll need to use a plugin that supports it.
