### ISSUE TITLE
Windows: isEnabled not implemented

### ISSUE THREAD

**Issue by TheBosZ** [randdusing/cordova-plugin-bluetoothle#491]
The `isEnabled` function isn't implemented.

I know that Windows functionality is experimental/limited, but it's a good idea to note the issues.

If I can, I may be able to contribute fixes to bring the Windows stuff up to snuff.

The command is:
`bluetoothle.isEnabled(function(result){console.log(result);});`

The error is:
> Missing Command Error

**Comment by randdusing** [comment]
Please reopen if @TheBosZ 's recent changes didn't fix this.
