### ISSUE TITLE
npm publish latest version

### ISSUE THREAD

**Issue by chrisfrancis27** [randdusing/cordova-plugin-bluetoothle#495]
I'm trying to use this code in another node module, but I'm getting errors about missing namespace `Bluetootle` which I believe you've fixed on master branch. However, latest version on npm is 4.4.3 which doesn't have the typo fixes. Could you push a new version up to npm please?

Cheers 🙌

**Comment by randdusing** [comment]
This is now published, reopen if you run into any issues
