### ISSUE TITLE
Windows10 uwp

### ISSUE THREAD

**Issue by FredGr** [randdusing/cordova-plugin-bluetoothle#501]
Hello,
Does the plugin work for windows10 uwp ?
Regards.
Fred

**Comment by TheBosZ** [comment]
Sorta. I would call it "alpha" quality. I'm building an app that works great on Android and iOS. 

Now my task is to port it to Windows 10 UWP. It kinda works. I can scan for devices, but that's about it.

**Comment by randdusing** [comment]
Please reopen if @TheBosZ 's recent changes didn't fix this.
