### ISSUE TITLE
Windows : unable to close

### ISSUE THREAD

**Issue by FredGr** [randdusing/cordova-plugin-bluetoothle#508]
On windows 10 when I close the BLE connection, the device remains active.
I looked inside the plugin code and it looks like services are being closed but not the actual device.
Also the success callback is never called.

**Comment by TheBosZ** [comment]
I've started a rework of the Windows 10 support here: https://github.com/TheBosZ/cordova-plugin-bluetoothle/tree/thebosz/rewrite-windows-10

Close() now works, and it uses MAC addresses as identifiers.

I'll be working on it more as Windows 10 support for our app has been identified as a priority.

**Comment by FredGr** [comment]
Hello,
Thanks for this very good initiative.
I managed to solve the closing issue by adding 'device.close() to the close function in BluetoothLEPlugin.js such as 👍       

var device = cachedDevice;
      device.close();
      device = null;
      var result = {status : "disconnected"};
      successCallback(result);
    
    } else {
      errorCallback({ error: "close", message: "Invalid parameter" });
    }
and adding cachedDevice initialization line 277
    cachedDevice = bleDevice;

Having done that the plugin is working quite well on Windows10 (connect read and write and close)

**Comment by randdusing** [comment]
Please reopen if @TheBosZ 's recent changes didn't fix this.
