### ISSUE TITLE
Windows: why use ContainerId instead of MAC Address?

### ISSUE THREAD

**Issue by TheBosZ** [randdusing/cordova-plugin-bluetoothle#509]
I'm working on getting our app that uses your great plugin to build on Windows 10 as an UWP project.

I'm finding that there's an issue with the way the "address" is handled. The plugin code treats the "ContainerId" as the device address instead of the MAC address.

This causes issues because of the way we have to get the DeviceInformation using `findAllAsync` which will wait for 30 seconds **every** time it tries to connect (because it's waiting for a timeout).

If we were to instead use the Device's MAC address, we could use `fromBluetoothAddressAsync` which is much quicker.

Are there design considerations that I'm not seeing for why ContainerId was chosen? If not, I'd like to rewrite the Windows 10 support to use MAC addresses instead. I think it'll be easier to maintain going forward.

**Comment by randdusing** [comment]
Please reopen if @TheBosZ 's recent changes didn't fix this.
