### ISSUE TITLE
How to write hexadecimal data directly instead of strings?

### ISSUE THREAD

**Issue by a1292999652** [randdusing/cordova-plugin-bluetoothle#521]
First of all, thank you very much for the plug-in written by the author. I use it very well! But now I need to write some instructions, but they are hexadecimal and not strings, such as `0x1b 0x68'. I have tried a lot, but failed to achieve what I wanted. I am very confused. If the author can help me, I am very grateful. The above text is translated from Chinese. I am not very good in English. I hope you can understand it. Thank you.

**Comment by randdusing** [comment]
Did you see the helper functions here? https://github.com/randdusing/cordova-plugin-bluetoothle#encodedstringtobytes

bytes to encoded string is probably what you need

**Comment by a1292999652** [comment]
Hello：
![2019-01-22 10 02 33](https://user-images.githubusercontent.com/31630317/51507694-02bfda00-1e2d-11e9-89fa-b62c7ef36dfc.png)
Now I have such a set of data, which is hexadecimal.
`this.printDataUnit8Array = this.$iconv.encode('1b68', 'hex');`
Then when I write, your plug-in does something for me.
`this.bluetooth.handleBtWrite(address, this.printDataUnit8Array);`
Will become：[
![2019-01-22 10 10 10](https://user-images.githubusercontent.com/31630317/51507878-f4be8900-1e2d-11e9-9f3d-4f5af45a24ee.png)
](url)
If used bytesToEncodedString
`this.bluetooth.handleBtWrite(address, this.bluetooth.handleBytesToEncodedString(this.printDataUnit8Array));`
[
![2019-01-22 10 10 10](https://user-images.githubusercontent.com/31630317/51508075-c1c8c500-1e2e-11e9-9b10-3a21947534a5.png)
](url)
What should I do now?

**Comment by randdusing** [comment]
You most likely need to use bytesToEncodedString. It's hard to say exactly what you need to do since I don't have the device.

**Comment by a1292999652** [comment]
Thank you very much for your answer. I decided to bypass this requirement and send strings directly. The printer will make corresponding API adjustments. I wish you a happy life.
