### ISSUE TITLE
Does this plugin work with a bluetooth 2.0 device ?

### ISSUE THREAD

**Issue by mignam** [randdusing/cordova-plugin-bluetoothle#525]
Hello, i was wondering if this plugin works with a bluetooth 2.0 device or just with BLE devices.

i explain myself, 

i need to communicate with a wireless stethoscope to get and store signals on a mobile phone. The stethoscope implement bluetooth 2.0. SDK for Android here: 

https://www.littmann.com/3M/en_US/littmann-stethoscopes/products/~/3M-Littmann-Software-Development-Kit/?N=5153440+8711017+3292368278&rt=rud

my questions are:
- can i do this with this plugin ? or should i directly implement a nativ app with android studio.
- Does this plugin can communicate with non-BLE device ?

Thanks !

**Comment by randdusing** [comment]
This plugin only supports BLE
