### ISSUE TITLE
Peripheral mode : Unable to add descriptor to characteristic

### ISSUE THREAD

**Issue by MajidAliKhanQuaid** [randdusing/cordova-plugin-bluetoothle#531]
How can i define a descriptor in characteristics ? Couldn't find a way in

**Comment by MajidAliKhanQuaid** [comment]
var params = {
  service: "1234",
  characteristics: [
    {
      uuid: "ABCD",
      permissions: {
        read: true,
        write: true,
        //readEncryptionRequired: true,
        //writeEncryptionRequired: true,
      },
      properties : {
        read: true,
        writeWithoutResponse: true,
        write: true,
        notify: true,
        indicate: true,
        //authenticatedSignedWrites: true,
        //notifyEncryptionRequired: true,
        //indicateEncryptionRequired: true,
      }
    }
  ]
};

How would i set default value for the descriptor

**Comment by MajidAliKhanQuaid** [comment]
And, How can i get that address parameter ?

**Comment by MajidAliKhanQuaid** [comment]
notify results in error, *address is not defined*

**Comment by randdusing** [comment]
It's not possible to set a default value for the descriptor with the current code.

The #notify() documentation is out of date. An address needs to be passed in. The address can be found from the status updates of #initializePeripheral()

**Comment by MajidAliKhanQuaid** [comment]
thanks @randdusing for the reply. Nice contribution 👍
