### ISSUE TITLE
Cordova 9 + Angular 8 can't find name bluetoothle

### ISSUE THREAD

**Issue by thebigandrei** [randdusing/cordova-plugin-bluetoothle#544]
Hello !

I would like to use this plugin in a cordova 9 + angular 8 app, is it possible?

I'm kind of new with cordova, and i don't really understand how to use the plugin in my angular code.

I installed the plugin correctly but can't access the plugin from my angular service (can't find name bluetoothle).

Let me know all informations you want me to give about my project.

Thanks.

**Comment by venatiodecorus** [comment]
you can access the plugin with `(<any>window).bluetoothle`

**Comment by thebigandrei** [comment]
This is the code in my angular service.

`(<any>window).bluetoothle.isEnabled(success=> {
      console.log(success);
    });`

This returns a new error : "Class not found".

Thanks for the effort =)
