### ISSUE TITLE
can't set android device name  when advertizing

### ISSUE THREAD

**Issue by gamjaradio** [randdusing/cordova-plugin-bluetoothle#550]
I can't change device name whne advertizing. It always shows my phone name.
my android is version 9, and 'cordova-plugin-bluetoothle": "^4.5.5".

var params = {
                services: [LIGHTBULB_SERVICE],
                service: LIGHTBULB_SERVICE,
                name: "hi",
                mode: "balanced",
                connectable: true,
                timeout: 20000,
                powerLevel: "high",
                includeDeviceName: true
            };
            
var v = await this.bluetoothle.startAdvertising(params);

this is my source,
is there a problem??

**Comment by randdusing** [comment]
The Android code doesn't use the name parameter. It just uses the includeDeviceName boolean. Readme most likely needs to be updated.

**Comment by gamjaradio** [comment]
thanks the comment :)
Then one more question, 
is it not possible to change the bluetooth name on Android?

**Comment by randdusing** [comment]
Not that I know of...unless you just update your device's actual name.

**Comment by ragcsalo** [comment]
There is a solution: in BluetoothLePlugin.java search this line
`BluetoothLeAdvertiser advertiser = bluetoothAdapter.getBluetoothLeAdvertiser();`

and insert these 2 lines below:
```
String advertisedName = obj.optString("name", "BTLE-default-name");
bluetoothAdapter.setName(advertisedName);
```

**Comment by gamjaradio** [comment]
It works 👍. Thanks a lot !!
