### ISSUE TITLE
how to add custom data on advertizing

### ISSUE THREAD

**Issue by gamjaradio** [randdusing/cordova-plugin-bluetoothle#552]
I want to set some information to Advertisement without connection read/write.
There is some for it in android bluetooth library, but I can not find here in cordova plugin.

**Comment by randdusing** [comment]
Looks like the readme is out of data. You want to use #startAdvertising() with manufacturerSpecificData
https://github.com/randdusing/cordova-plugin-bluetoothle/blob/master/src/android/BluetoothLePlugin.java#L738

**Comment by gamjaradio** [comment]
thanks a lot :). I cat make it work with manufacturerSpecificData.

> Looks like the readme is out of data. You want to use #startAdvertising() with manufacturerSpecificData
> https://github.com/randdusing/cordova-plugin-bluetoothle/blob/master/src/android/BluetoothLePlugin.java#L738
