### ISSUE TITLE
Infinite loop when adding descriptors

### ISSUE THREAD

**Issue by PacificNorthwest** [randdusing/cordova-plugin-bluetoothle#556]
Hey, just wanted to say I appreciate the work you're doing on your contribution.
Thought there's a pretty severe problem that causes an infinite loop whenever one tries to add a characteristic descriptor on Android.

Loop parameters seems to be off here:
https://github.com/randdusing/cordova-plugin-bluetoothle/blob/2c35583c073e9add0babd5b7e9302af47ed7bb85/src/android/BluetoothLePlugin.java#L563

And also here:
https://github.com/randdusing/cordova-plugin-bluetoothle/blob/2c35583c073e9add0babd5b7e9302af47ed7bb85/src/android/BluetoothLePlugin.java#L567

Figured you might want to check into it. Thanks!

**Comment by randdusing** [comment]
Oops, that's pretty bad. I'm surprised this wasn't found earlier!

**Comment by randdusing** [comment]
This has been fixed in v4.5.6
