### ISSUE TITLE
peripheral mode: Advertising frequency

### ISSUE THREAD

**Issue by pavlosero** [randdusing/cordova-plugin-bluetoothle#560]
Hi,
I can't find any information on the description.
I want to use the plugin on Android device. 
What is advertsing interval in peripheral mode and is there a way to change it?

**Comment by ndrake** [comment]
When you call `startAdvertising` on Android you can specify a parameter to set the frequency.

See https://github.com/randdusing/cordova-plugin-bluetoothle/blob/2c35583c073e9add0babd5b7e9302af47ed7bb85/types/index.d.ts#L677

The values map to ADVERTISE_MODE_* values here: https://developer.android.com/reference/android/bluetooth/le/AdvertiseSettings.html
