### ISSUE TITLE
initialize does not trigger status changes

### ISSUE THREAD

**Issue by pallinp** [randdusing/cordova-plugin-bluetoothle#570]
Hi,

I've got a little problem with the "initialize" method.

The first subscription trigger is working and I've got the Bluetooth status. When I turn on or turn off the Bluetooth later, the subscription is not triggered anymore.

Am I missing something ?

My plan was to use the subscription to manage properly my resources when the Bluetooth is turned off wildly.

Here is my code:

```ts
this.ble.initialize({
  'request': true,
  'statusReceiver': false,
  'restoreKey': 'sandbox'
}).subscribe((status) => {
  console.log(status);
});
```

I'm using Ionic 4 and the version 4.5.6 of the Bluetooth plugin.

I've got the same behavior on a Samsung Galaxy tab 3 running Android 9 and on an Xperia G3212 running Android 8.

Thanks in advance

Regards

**Comment by JesperBalslev** [comment]
Just to add on this, It works as expected on iOS but not on Android.

**Comment by JesperBalslev** [comment]
I fixed the issue in the plugin (Android) - but before i make a PR - i will dig deeper and see if there are other  issues i can fix...

**Comment by randdusing** [comment]
statusReceiver => true doesn't help with this?

**Comment by pallinp** [comment]
@randdusing: It does ! I misunderstood the documentation. Thanks.

**Comment by OJ7** [comment]
> statusReceiver => true doesn't help with this?

It seems like either the code or documentation needs updating.
On iOS, it triggers status changes by default. (Haven't tested with with `statusReciever: false`)
On Android, it only triggers it when using `statusReciever: true`.
