### ISSUE TITLE
ACCESS_FINE_LOCATION is required for Android 10

### ISSUE THREAD

**Issue by alexhisen** [randdusing/cordova-plugin-bluetoothle#579]
On Android, if you target SDK 29 (Android 10), then in hasPermission/requestPermission() you must use ACCESS_FINE_LOCATION instead of ACCESS_COARSE_LOCATION. The manifest should also request both of them.

**Comment by randdusing** [comment]
It looks like there are also some permission changes required for scanning in the background. I don't have any Android devices to test on anymore, so hopefully someone else can raise a PR.

https://developer.android.com/about/versions/10/privacy/changes#app-access-device-location

**Comment by lazydan** [comment]
The scan() function would work fine on Android 10 after i add the ACCESS_FINE_LOCATION permission to plugin.xml file.

**Comment by NunoSav** [comment]
I've tried to change COARSE to FINE in the source code and it worked and then i tried changing plugin.xml seperately and it did not work.
