### ISSUE TITLE
manufacturerSpecificData on IOS ?

### ISSUE THREAD

**Issue by cmorillo** [randdusing/cordova-plugin-bluetoothle#580]
Hi there,

Thanks for the plugin, is great, any way to pass on the manufacturerSpecificData on IOS?
It doesn't work for me and return the Service name.

Cheers,

Carlos

**Comment by cmorillo** [comment]
advertisement = advertisement hash with the keys specified here (iOS)

**Comment by ndrake** [comment]
This isn't possible as Apple's Core Bluetooth API doesn't allow specifying manufacturer specific data. 

https://developer.apple.com/documentation/corebluetooth/cbperipheralmanager/1393252-startadvertising

`An optional dictionary containing the data you want to advertise. The peripheral manager only supports two keys: CBAdvertisementDataLocalNameKey and CBAdvertisementDataServiceUUIDsKey.`

**Comment by cmorillo** [comment]
Hi, in my case, I will be using the name property... that should do it.
