### ISSUE TITLE
reconnect signature is wrong

### ISSUE THREAD

**Issue by chegewara** [randdusing/cordova-plugin-bluetoothle#588]
This repository seems to be no longer maintained, but as a remainder and maybe if someone else will search for it. Reconnect function seems to have wrong signature. I found this is correct one:
```
reconnect(params: {
address: string;
}): Observable<DeviceInfo>;
```

**Comment by randdusing** [comment]
I still "maintain" it, but not as much as I used to. PRs are appreciated!

**Comment by randdusing** [comment]
Where is this an issue? This code base doesn't mention any observables.

**Comment by chegewara** [comment]
Great, thanks for that plugin, i like it even if i am new to ionic.
I will try to create PR, its easy fix.

**Comment by chegewara** [comment]
Its index.ts. Let me find it.

**Comment by chegewara** [comment]
Path to file is:
`node_modules/@ionic-native/bluetooth-le/ngx/index.d.ts`

**Comment by randdusing** [comment]
That's a wrapper for this plugin, so you'll need to raise the issue with them.

There code looks correct: https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/bluetooth-le/index.ts

**Comment by chegewara** [comment]
This line:
https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/bluetooth-le/index.ts#L575

**Comment by chegewara** [comment]
I did some debug and print logs and returned is straight DeviceInfo, not as status: DeviceInfo.

**Comment by randdusing** [comment]
It's an issue with Ionic's plugin wrapper. I didn't notice the { status: DeviceInfo } the first time. You should raise a PR to fix it.

**Comment by chegewara** [comment]
Great, thanks for explanation.
