### ISSUE TITLE
iOS crashes on notify

### ISSUE THREAD

**Issue by a-sac** [randdusing/cordova-plugin-bluetoothle#598]
Hey there,

I tried to connect two android devices using subscribe and notify. No problems so far.

When I try to connect an Android and an iPhone, the app crashes on notify. Everything is working except notify. And I don't even receive an error, the app simply crashes.

The code:

```
subscribed(ble) {
    this.setMessage(ble.address + " subscribed");

    var params = {
      "service":"1234",
      "characteristic":"ABCD",
      "value": "V3JpdGUgSGVsbG8gV29ybGQ"
    };

    params["address"] = ble.address;

    this.bluetoothle.notify(params).then(
      response => this.setMessage(JSON.stringify(response)),
      error => this.setMessage(JSON.stringify(error))
    );
  }
```

**Comment by randdusing** [comment]
Any logs from the crash?

**Comment by a-sac** [comment]
@randdusing 
`MyApp[76071:804074] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: value != nil'`

**Comment by a-sac** [comment]
Xcode redirects me to **line 460** of 

> BluettothPlugin.m 

` BOOL result = [peripheralManager updateValue:value forCharacteristic:checkCharacteristic onSubscribedCentrals:nil]; //TODO need to store CBMutableCharacteristic `

Sorry if I'm doing something stupid, I'm new to all Ionic/ Mobile ecosystem :/

**Comment by randdusing** [comment]
This may be a base64 encoding issue. There should be an equals sign at the end

**Comment by a-sac** [comment]
@randdusing it worked, thanks!

**Comment by randdusing** [comment]
The readme values look correct, not all of them end in an equals, but that one did :)
