### ISSUE TITLE
Android: stopAdvertising is called automatically after startAdvertising

### ISSUE THREAD

**Issue by JorgeMorata** [randdusing/cordova-plugin-bluetoothle#606]
Good Morning,

I am using the library to develop an application that allows using the mobile phone as a BLE and at the same time make scans of other BLEs around that have the same application.

To do this, I perform startAdvertising (which works on both iOS and Android) and then scans that also return the other mobile phones well.

The problem comes, since in Android, immediately after performing startAdvertising (and for example from an iOS detect the android phone), the Android phone is no longer visible.

The application performs a startScan every 30 seconds to find new BLE devices (while the adverstising is on)

Checking the android system logs I see that a call is made to stopAdvertising but it is not made from my code. It seems to be called from the system.

The traces I have found are the following in case they help in the diagnosis:

Android 7:
```
05-14 01:30:47.968  4458  4458 I chromium: [INFO:CONSOLE(1114)] "Bluetooth Peripheral Advertising started: {"mode":1,"timeout":1000,"txPowerLevel":3,"isConnectable":false,"status":"advertisingStarted"}"
05-14 01:30:48.048   805   805 I aptouch_daemon: check_afe_status, idle in. 100
05-14 01:30:48.224  4458  4541 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
05-14 01:30:48.674  4458  4458 I BluetoothLeAdvertiser: stopAdvertising is called
05-14 01:30:48.702  1217  1806 I TrafficMonitor: update:rxPkts:29,txPkts:35,rxBytes:20049,txBytes:5124
05-14 01:30:48.702  1217  1806 I TrafficMonitor: no expired. level:2
05-14 01:30:48.702  1217  1806 I TrafficMonitor: gettimer:interval=2000
05-14 01:30:48.703  1217  1806 I TrafficMonitor: during_ms:2002,period_ms:2000
05-14 01:30:48.703  1217  1806 I TrafficMonitor: count:226,rx_sum:29,tx_sum:35,rxBytes:20049,during_ms:2002,rx_speed:10014.485514485516,tx_speed:2559.44055944056,rto:0.8285714285714286
05-14 01:30:48.734  4458  4541 D SERVER  : Handling local request: http://localhost/33-es2015.js
05-14 01:30:48.736  4458  4541 D SERVER  : Handling local request: http://localhost/75-es2015.js
05-14 01:30:48.737  4458  4541 D SERVER  : Handling local request: http://localhost/69-es2015.js
05-14 01:30:48.738  4458  4541 D SERVER  : Handling local request: http://localhost/29-es2015.js
05-14 01:30:48.738  4458  4542 D SERVER  : Handling local request: http://localhost/17-es2015.js
05-14 01:30:48.765  2139  3458 D ConnCureStateMonitor: handleMessage: msg[4]
05-14 01:30:48.767  2139  3458 D ConnCureStateMonitor: canPerformConnCure: wifi link normally
05-14 01:30:48.906 21705 24945 E bt_stack: [ERROR:btm_ble_multi_adv.cc(645)] Invalid or no active instance
```

Android 8:
```
05-14 13:42:53.956 10962 11534 W CordovaPlugin: Attempted to send a second callback for ID: BluetoothLePlugin1803884166
05-14 13:42:53.956 10962 11534 W CordovaPlugin: Result was: {"service":"00001802-0000-1000-8000-00805f9b34fb","status":"serviceAdded"}
05-14 13:42:53.957 10962 11534 W PluginManager: THREAD WARNING: exec() call to BluetoothLePlugin.addService blocked the main thread for 39ms. Plugin should use CordovaInterface.getThreadPool().
05-14 13:42:53.997 10962 11534 D BluetoothAdapter: isLeEnabled(): ON
05-14 13:42:54.026 10962 11534 D BluetoothAdapter: isLeEnabled(): ON
05-14 13:42:54.036  1852  1863 D BluetoothAdapterService: getAdapterService() - returning com.android.bluetooth.btservice.AdapterService@b9b4422
05-14 13:42:54.037  1852  1863 D BtGatt.AdvertiseManager: startAdvertisingSet() - reg_id=-3, callback: android.os.BinderProxy@de0e26
05-14 13:42:54.038 10962 11534 W PluginManager: THREAD WARNING: exec() call to BluetoothLePlugin.startAdvertising blocked the main thread for 68ms. Plugin should use CordovaInterface.getThreadPool().
05-14 13:42:54.057  1852  1996 D BtGatt.AdvertiseManager: onAdvertisingSetStarted() - reg_id=-3, advertiser_id=1, status=0
05-14 13:42:54.162 10962 10962 D SystemWebChromeClient: http://localhost/status-status-module-es2015.js: Line 1114 : Bluetooth Peripheral Advertising started: {"mode":1,"timeout":1000,"txPowerLevel":3,"isConnectable":false,"status":"advertisingStarted"}
05-14 13:42:54.162 10962 10962 I chromium: [INFO:CONSOLE(1114)] "Bluetooth Peripheral Advertising started: {"mode":1,"timeout":1000,"txPowerLevel":3,"isConnectable":false,"status":"advertisingStarted"}", source: http://localhost/status-status-module-es2015.js (1114)
...
05-14 13:42:55.060  1852  1996 D BtGatt.AdvertiseManager: onAdvertisingSetEnabled() - advertiser_id=1, enable=false, status=0
...
05-14 13:42:55.512 10962 10962 D BluetoothLeAdvertiser: stopAdvertisingSet(): ON
05-14 13:42:55.514  1852  1863 D BtGatt.AdvertiseManager: stopAdvertisingSet() android.os.BinderProxy@de0e26
```

Is it possible that if a startScan is performed while advertising is on, stopAdvertising is called on Android?

I have the next configuration on config.xml:
```
...
<preference name="android-minSdkVersion" value="23" />
<preference name="android-targetSdkVersion" value="28" />
...
<platform name="android">
        <config-file parent="/manifest" target="AndroidManifest.xml">
            <uses-permission android:name="android.permission.BLUETOOTH" />
            <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
            <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
            <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
            <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
        </config-file>
        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application">
            <application android:networkSecurityConfig="@xml/network_security_config" />
        </edit-config>
        <resource-file src="resources/android/xml/network_security_config.xml" target="app/src/main/res/xml/network_security_config.xml" />
...
</platform>
...
<engine name="android" spec="^8.1.0" />
<engine name="ios" spec="^5.1.1" />
<plugin name="cordova-plugin-bluetoothle" spec="^4.5.10" />
...
```

If more information is needed, do not hesitate to request it.

Thank you.

**Comment by mattkhaw** [comment]
@JorgeMorata I'll throw in my 2 cents here. I'm also in the midst in developing an app which uses both central and peripheral functions on the same device and both functions are running in tandem as well. I'm doing scanning and advertising at the same time. It seems to be working fine. I'm using Android 6 btw. Maybe it is something else that is causing issues?

**Comment by JorgeMorata** [comment]
Hi! 

I don't know... In iOS works perfectly, and scanning from an Android Device, find the device correctly, but when the device i'm trying to scan is Android, only in the first milisiconds the service/device is available to others devices.

On the occasions the device is founded, i'm trying to connect to it automatically and it's already stopped/dissapeared (so is stopped in milliseconds).

Thank for your response!

**Comment by mattkhaw** [comment]
Weird indeed. I've only tested between iOS and Android. I haven't test Android with Android or iOS with iOS due to the limited amount of devices I have. Maybe I'll try it out and see.

**Comment by WWWMARIO** [comment]
Your advertising timeout is set to 1000 ms.

Try setting your AdvertisingParams to a higher timeout.

export interface AdvertisingParamsAndroid {
    service: string;
    mode?: AdvertiseMode;
    connectable?: boolean;
    **_timeout?: number;_**
    txPowerLevel?: TxPowerLevel;
    manufacturerId?: number;
    manufacturerSpecificData?: any;
    includeDeviceName: boolean;
    includeTxPowerLevel: boolean;
}

**Comment by JorgeMorata** [comment]
> Your advertising timeout is set to 1000 ms.
> 05-14 01:30:47.968 4458 4458 I chromium: [INFO:CONSOLE(1114)] "Bluetooth Peripheral Advertising started: {"mode":1,"**_timeout":1000_**,"txPowerLevel":3,"isConnectable":false,"status":"advertisingStarted"}"
> 
> Try setting your AdvertisingParams to a higher timeout.
> 
> export interface AdvertisingParamsAndroid {
> service: string;
> mode?: AdvertiseMode;
> connectable?: boolean;
> **_timeout?: number;_**
> txPowerLevel?: TxPowerLevel;
> manufacturerId?: number;
> manufacturerSpecificData?: any;
> includeDeviceName: boolean;
> includeTxPowerLevel: boolean;
> }

F****!!! I didn't set the timeout and i thought it was "0"... Thank you for your response! Probably it fix the problem (Because of the waiting, I finally did the app Android Native and it works perfectly so I discontinued the Ionic Android App).

Thank to all for the help!

**Comment by asif166037** [comment]
Thank you so much @jmoratat !!
