### ISSUE TITLE
Scan successful but not get the device's address

### ISSUE THREAD

**Issue by shern91** [randdusing/cordova-plugin-bluetoothle#613]
I using the startScan() method but get the scan's result like below, not get the device address.
`{"address":"02:22:F0:00:18:F0","name":"MPT-III","rssi":-46,"advertisement":"AgECEQbyw/CuqfoVjJ1JrnNxCoHnCf9LQwIi8AAY8AIBAggJTVBULUlJSQAAAAAAAAAAAAAAAAAAAAAAAAA=","status":"scanResult"}`

**Comment by symun92** [comment]
**"address":"02:22:F0:00:18:F0"**
This is the the device's address / identifier. It is actually bluetooth address
