### ISSUE TITLE
BLE for iOS: Device gets immediately disconnected after connecting

### ISSUE THREAD

**Issue by sammy00747** [randdusing/cordova-plugin-bluetoothle#620]
@randdusing Thanks for such a great plugin!

I am trying to build a project, where the Android/iOS app is a central device, and the Raspberry Pi is a peripheral device. They are to form a connection, and the central device will be sending read/write requests to the peripheral device. While the Android app is able to form a stable connection, the iOS app gets disconnected immediately after connection.

Ionic:

   Ionic CLI          : 5.4.16 (/Users/nits_mac4/.nvm/versions/node/v10.16.3/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.5
   @ionic/app-scripts : 3.2.2

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : ios 6.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 11 other plugins)

Utility:

   cordova-res (update available: 0.12.2) : 0.10.0
   native-run                             : not installed

System:

   ios-deploy : 1.9.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/Users/nits_mac4/.nvm/versions/node/v10.16.3/bin/node)
   npm        : 6.9.0
   OS         : macOS Catalina
   Xcode      : Xcode 11.5 Build version 11E608c

Any help is greatly appreciated

**Comment by ArMouReR** [comment]
Did you succeeded with your project ? I have the same issue with Raspberry Pi3.
What kind of stack do you use on Raspberry ?
