### ISSUE TITLE
Installing Version 5.x.x not possible

### ISSUE THREAD

**Issue by ebeling** [randdusing/cordova-plugin-bluetoothle#632]
Many thanks  for new release! How can I install this? I use current cordova-cli (9.0.0 with  cordova-lib@9.0.1). If I call 

`cordova plugin add cordova-plugin-bluetoothle`

following message appear:

`Unmet project requirements for latest version of cordova-plugin-bluetoothle:
    cordova (9.0.1 in project, >=100 required)
Fetching highest version of cordova-plugin-bluetoothle that this project supports: 4.5.14 (latest is 5.0.0)`

**Comment by randdusing** [comment]
This is odd. I haven't changed any dependencies in a long time... I wonder if anyone else is having this problem.

**Comment by randdusing** [comment]
Ahh, it must be related to this line:
https://github.com/randdusing/cordova-plugin-bluetoothle/blob/master/package.json#L35

Let me see what this actually does

**Comment by ebeling** [comment]
Thank you for release 5.0.2. I have tested with cordova-cli 10.0.0 and it works now!
