### ISSUE TITLE
bluetoothle is not defined. var bluetoothle; did not help

### ISSUE THREAD

**Issue by schumannd** [randdusing/cordova-plugin-bluetoothle#64]
Hi,
I have been trying to get the plugin to work for the last few hours. I might be missing a key understanding on how it is supposed to work. I read here (http://www.randdusing.com/2014/02/19/bluetooth-low-energy-plugin-for-phonegap/) that adding var bluetoothle; to my "index.js" might solve the problem. It didn't: "Cannot call method 'initialize' of undefined". Are there other steps I can take?

I added the plugin to my project via commandline.
I also tried copying the bluetoothle.js into my project tree and loding that. This gave me two other errors: Uncaught ReferenceError: modul is not defined, Uncaught ReferenceError: cordova is not defined

solution:
I just used cordova incorrectly. If you have the same issues as I had make sure, that you call app.initialize() and have the corresponding functions. Take a look at the initial setup when you start a cordova project and DON'T jsut replace the www folder with your content (thats what I did)

**Comment by JhonnyJason** [comment]
Hello,  :-)

I'm baffled having the same Problem. 
The bluetoothle object is not defined and I have no clue why this is. :-/

I'm not sure if the issue is in the package, or just in my workflow - I described it here at Stackoverflow.

[http://stackoverflow.com/questions/38106281/why-do-none-of-my-plugins-work-for-apache-cordova/38532366#38532366](url)

On my side other plugins work when applying the same procedure.

Can somebody verify that the actual package, using the latest Phonegap cli, is working in that way?

And if the package is working - what could be my blind spot there? As I 'm sure I'm using cordova the right way^^... 

Cheers! And thanks for this Plugin anyways :-)

**Comment by randdusing** [comment]
@JhonnyJason Is that your code on StackOverflow? Try removing the ```var bluetoothle;```

**Comment by JhonnyJason** [comment]
On 23 July 2016 at 18:56, Rand Dusing <notifications@github.com> wrote:

> @JhonnyJason <https://github.com/JhonnyJason> Is that your code on
> StackOverflow? Try removing the var bluetoothle;
>
Yes it is, It is the same result without the variable :-/
The only difference is then that the script dies because of an "uncaught
ReferenceError"

**Comment by randdusing** [comment]
Do you use Ionic? Try using the example in the Angular wrapper: https://github.com/randdusing/ng-cordova-bluetoothle

**Comment by rogerclarkmelbourne** [comment]
I get the same error.



using the standard PhoneGap Hello world 

```
var app = {
    // Application Constructor
    initialize: function() {
        this.bindEvents();
    },
    // Bind Event Listeners
    //
    // Bind any events that are required on startup. Common events are:
    // 'load', 'deviceready', 'offline', and 'online'.
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    // deviceready Event Handler
    //
    // The scope of 'this' is the event. In order to call the 'receivedEvent'
    // function, we must explicitly call 'app.receivedEvent(...);'
    onDeviceReady: function()
	{		
        app.receivedEvent('deviceready');		
    },
    // Update DOM on a Received Event
    receivedEvent: function(id) {

        console.log('Received Event: ' + id);
		log("Device ready", "status");

		new Promise(function (resolve) 
		{
			bluetoothle.initialize(resolve, { request: true, statusReceiver: false });
		}).then(initializeSuccess, handleError);			

etc 
etc
```

I get DEVICE IS READY displayed in the "output" div, but under it I get "REFERENCERRROR BLUETOOTHLE IS NOT DEFINED" from the handleError() 


I installed the plugin via config.xml

`    <plugin name="cordova-plugin-bluetoothle"         source="npm" spec="~4.3.0" />	`

And looking in build.phonegap.com

I can see the plugin is installed 

`cordova-plugin-bluetoothle    	npm 	~4.3.0 	4.3.0 	n/a 	android,ios,winphone`

And in Phonegap's log I can see

```
Fetching plugin "cordova-plugin-bluetoothle@~4.3.0" via npm
Installing "cordova-plugin-bluetoothle" at "4.3.0" for android
```

Any ideas what I'm missing ?

**Comment by JhonnyJason** [comment]
Hi!
Well I gues it does not help with your Problem as you are testing it with the "real" App.

I was testing using the Phonegap App... there only the bundled Plugins are available, and "installing" the Plugin for Android builds and stuff does not install it to the Phonegap App - one would need to build the Phonegap App oneself installing the Plugins one needs to it, to do faster testing using the Phonegap App.

For your Problem I just have a trivial guess :D 
In the index.html did you put the script including yourcode.js below or on top of the the cordova.js include?

When on top this might be a problem.

**Comment by rogerclarkmelbourne** [comment]
@JhonnyJason 

I think this is a problem with build.phonegap.com rather than the plugin

I don't think its correctly building the plugin into the apk file

So I've given up on using build.phonegap.com as it looks like its not the best way to do initial development, and I've installed npm and cordova etc locally on my PC, and now things work a lot better

(Albeit I'm using a different ble plugin now as well, but none of the ble plugins worked when I used build.phonegap.com)

**Comment by JhonnyJason** [comment]
ok, well that is weird... 

As I had the problem and did not figure it out then for long I also switched to another plugin.

For me the builds at phonegap build did work and the Plugin was available (for both). Would not have any Idea what might be the difference that phonegap build behaves differently for us.

**Comment by JhonnyJason** [comment]
ok, well that is weird... 

As I had the problem and did not figure it out then for long I also switched to another plugin.

For me the builds at phonegap build did work and the Plugin was available (for both). Would not have any Idea what might be the difference that phonegap build behaves differently for us.

**Comment by rogerclarkmelbourne** [comment]
OK.

If I get it working on builds.phonegap.com I'll repost how ;-)
