### ISSUE TITLE
Readme has conflicting android minimum requirements

### ISSUE THREAD

**Issue by ab12gu** [randdusing/cordova-plugin-bluetoothle#682]
"Android 4.3 or higher, Android Cordova library 5.0.0 or higher, target Android API 23 or higher"

Platform: Android 4.3 supports API 18 or lower
Android API 23 supports Android Platform 6.0 or higher

Since API 23 is the higher of the two, I believe the platform should be 6.0 rather than 4.3.
If I am mistaken, please let me know.

**Comment by randdusing** [comment]
Mind raising a PR? :)

**Comment by ab12gu** [comment]
Yeah I can do that :)

**Comment by alexhisen** [comment]
Actually, Android Cordova 5.x can be used with much higher target APIs. Those two aspects are independent.

**Comment by ab12gu** [comment]
I'm confused about this comment. The updated readme with this PR should address what you stated. See solution: #686

**Comment by alexhisen** [comment]
The update is not actually accurate. This plugin DOES work with Android Cordova 5 just fine as long as you target API 23 or higher.

**Comment by ab12gu** [comment]
"Android Cordova library 5.0.0 or higher target Android API 23/Platform 6.0 or higher (support for older Android versions should use versions 2.4.0 or below)"

Unsure how this isn't the same thing? Unless you are nitpicking the wording... there was an accidental comma, but thats the only issue I saw...

**Comment by alexhisen** [comment]
I guess the Platform 6.0 part is confusing and unnecessary.

**Comment by ab12gu** [comment]
Seems standard: https://source.android.com/setup/start/build-numbers shows versioning which is just the specific android platform android x [1 -> 12+]. They use platform terminology: https://developer.android.com/studio/releases/platforms.
