### ISSUE TITLE
Connecting to a not reachable device block next calls

### ISSUE THREAD

**Issue by joseandrespg** [randdusing/cordova-plugin-bluetoothle#72]
Hi!

First of all, thanks and great work! The example is fantastic to learn how to use it :)

    Disclaimer: I only can test it on Android.

Now, the problem I found, I'll try to explain the call's flow to be more clear:

1- Initialize, all is OK.
2- Try to connect to a known address BUT this device is turned off, so is not reachable.
3- As your example, I set a timeout of 5 seconds to exit.
4- As expected, the timeout trigger the callback, that give me an error
5- On error received, I try to disconnect from device, the disconnect success callback return only one message -> status:"disconnecting" .
6- Then nothing more happen, so the device is not totally "disconnected"

All the next calls return errors, for example if I try to connect again: "Device previously connected, reconnect or close for new device".

Summarising: is there a bug when the connect method doesn't get fully connected that make impossible to do more calls.

**Comment by randdusing** [comment]
This problem shouldn't exist as of 2.0.0 since you can now connect to multiple devices at once.

**Comment by mrquincle** [comment]
Is it possible to create a state with which we know that there has been a connection attempt? Akin to `bluetoothle.isConnected`, but then `bluetoothle.isConnecting`? Then I know when to do a connect versus a reconnect, without actually trying a connect first.

**Comment by randdusing** [comment]
Good idea, I'll add a function bluetoothle.wasConnected

**Comment by randdusing** [comment]
wasConnected is now in the master branch and will be part of 4.1.0. Still working on a few other things to add to 4.1.0
