### ISSUE TITLE
128 bit uuid for scan on Android doesn't like dashes

### ISSUE THREAD

**Issue by mojo3344** [randdusing/cordova-plugin-bluetoothle#73]
Using the example in the readme, I modified it to talk to some hardware with 128 uuid's for services and characteristics by changing the battery uuid's to match my hardware. On IOS, it works great, but on Android, it doesn't seem to like having dashes in the uuid for the call to scan. Specifically, this workaround shows the problem:

````
var batteryServiceUuid = "00001523-1212-efde-1523-785feabcd123";
var batteryLevelCharacteristicUuid = "00001526-1212-efde-1523-785feabcd123";
...
  // on android, delete out the dashes for the scan call
  var batteryServiceUuidForScan = batteryServiceUuid
  if (window.device.platform == androidPlatform)
  {
    batteryServiceUuidForScan = batteryServiceUuidForScan.replace(new RegExp('-', 'g'),"")
  }

  var paramsObj = {"serviceUuids":[batteryServiceUuidForScan]};
  bluetoothle.startScan( startScanSuccess , startScanFailure, paramsObj )
````

I'm happy with this workaround for my purposes, but perhaps the scan call should do this itself?

Morgan

**Comment by randdusing** [comment]
@mojo3344  What versions / devices are dashes working / not working for you?

**Comment by mojo3344** [comment]
I'm sorry to say that I don't have it set up to test at this point. This was from a while ago, but my memory is that I traced my issues to the firmware I was developing for the device - I think you can close this issue.

**Comment by randdusing** [comment]
Ahh ok, well if you run into again, just reopen.
