### ISSUE TITLE
Android 12 requestPermissionBtConnect - it allows nearby devices BUT crash and exit

### ISSUE THREAD

**Issue by Sebartus** [randdusing/cordova-plugin-bluetoothle#736]
In Android 12 ( in Android 11 without this new method everything works fine ) I add new method:
`bluetoothle.requestPermissionBtConnect(requestPermissionSuccess, requestPermissionError);`

In app I got new popup to allow Nearby devices and in Settings >> Location >> App Name I can see it:

![bpe](https://user-images.githubusercontent.com/7703206/191867242-78e7987c-958a-4d83-b1e2-dd5f30f027f9.png)

but then app crash and exit. In log i can see error:
`java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for AttributionSource`

The only solution is to go Settings >> Location >> App Name and manualy Don’t allow
and again Allow Nearby devices to work correct. This situation occurs both in the simulator and on the real device.

**Comment by Cyb0org** [comment]
Do you have `BLUETOOTH_CONNECT` permissions in the `AndroidManifest.xml`?

**Comment by Sebartus** [comment]
> Do you have `BLUETOOTH_CONNECT` permissions in the `AndroidManifest.xml`?

Yes I have `BLUETOOTH_CONNECT` but I solved the problem. 

SOLUTION:
Correct sequence is:
1. `bluetoothle.initializePeripheral(success, error, params);`
2. `bluetoothle.hasPermissionBtConnect(hasPermissionSuccess);`
3. `bluetoothle.requestPermissionBtConnect(requestPermissionSuccess, requestPermissionError);` - the lack of this step caused an error
4. bluetoothle.isLocationEnabled(isLocationEnabledSuccess, isLocationEnabledError);
...
