### ISSUE TITLE
Android performance on peridodically writing | Command queuing

### ISSUE THREAD

**Issue by pfried** [randdusing/cordova-plugin-bluetoothle#74]
Hey Rand,

i saw some talk about queues in #32 where you said something about plans to implement a queue.

I wanted to share some experience with my current project. Maybe i can present it somewhere on the internet when my university allows to do so (documents are all in german, but code is not).

I do have a remote controlled car which is run by a Atmel XMega128A1 with a nRF8001 by Nordic Semiconductor.

I think the chip does a good job and i was able to port the driver from Nordic's Arduino Implementation to the XMega with C. Altough my chip should be able to deal with about 122 connections per second with 1-2 transmissions per connection in comes down to a much much smaller transmission rate on android. My Controller should be able to handle a data rate of about 2,75 KB/s.

I already had to stuff some characteristics into one because it increases performance if you do not have to handle 23 Characteristics as i had in my first draft (now its 5).

I do control steering and acceleration of the car by transmitting them periodically to the car. I do this with a timeout of 175ms in javascript which results in a 180ms timeout on the native GATT. As i do transmit 6 Bytes per transmission this is **freaking bad** performance. Practically i would want to transmit at least each 50ms.

If i try to lower the timeout it will start to act weird (queuing on the native implementation) which results in the car executing one command after another but time shifted as the transmission cant handle more than these 5-6 transmissions per second. This also happens for bad signal strengths.

On the beginning of the project i hoped to get a good transmission speed via BtLE but as it turns out Android is not able to handle many transmissions with cordova and your plugin. I haven't tried to implement this in Java as i do not have time currently but i guess the result will be not much better. I looked into the docs for Android and there is not much to improve.

I implemented a queue once and this was even worse that fire & forget as it was not applicable for my remote controlled car.

But back to the queue: I think it is a good idea to have a queue as it could help to avoid common problems. Even i have some timeout calls in my code to sequence the notification subscriptions on startup. In case of the driving the car i do fire the write commands each 175ms and hope it works out.

Do you have some experience with writing to a single characteristics periodically or somebody else?

**Comment by kgillespieanaren** [comment]
The performance issues you describe are not related to Phonegap or the BluetoothLE plugin. I have written native Android Apps and iOS Apps for Bluetooth LE and consistently run into a performance wall with Android. Typically the performance is a magnitude worse on Android than iOS and it is frustrating. I have worked around the problem by trying to shrink the size of my characteristics as small as possible but still have very poor responsive behavior.

I have implemented queuing systems in my projects, but all they do is make sure that the message arrive in an orderly fashion they do nothing to improve the performance on android.

**Comment by pfried** [comment]
I totally agree, i die some measurements and basically cordova doesnt affect the performance at all. I hope the performance improves in the future as the current state is really bad

**Comment by randdusing** [comment]
Thanks for the information. I'm happy to find out it wasn't something I did incorrectly :)

**Comment by kgillespieanaren** [comment]
One thing I was considering doing for the BluetoothLE plugin was building a command queue into the Android part of the plugin. It appears that iOS is does this for the user's application for them and I want the plugin to have similar and consistent behavior across the different platform. So a command queue and making sure that the Android subsystem is read for the next command each and every time.

**Comment by randdusing** [comment]
I hadn't heard about iOS doing that, is it in the docs or elsewhere?

**Comment by kgillespieanaren** [comment]
I never could find any docs, but I ran some test and either,

A.) It happens so fast it doesn't matter
B.) iOS is queuing.

Another interesting fact the ACER Iconia A3-A20FHD is an android tablet that uses a Mediatek chipset and it does do queueing. It's the best Android device when it comes to BLE

**Comment by randdusing** [comment]
3.2.0 has a writeQ function. It takes data, splits it into 20 bytes, and writes it as soon as possible.

Since iOS already queues, there's not much performance benefit besides not wasting time with the app -> plugin code and plugin code -> app "bridge".

On Android, the performance increase is much better. When each 20 byte packet is written, onCharacteristicWrite is called, and then the next 20 bytes are written. This could be done from the app level, but traversing the app -> plugin and plugin -> app "bridge" eats up a lot time.

This code could come in very handy when doing an OTA transfer. Write a bunch of bytes, wait for a notification, write more bytes, continue until the file is transferred.

But it probably doesn't help if you're just trying to send a bunch of "unrelated" commands as quickly possible. I'll take another look at trying to implement a better queue solution.

**Comment by randdusing** [comment]
Current master now has queueing for read and write operations.
