### ISSUE TITLE
hasPermissionBtScanAction and hasPermissionBtConnectAction should always return true on AndroidSDK < 31

### ISSUE THREAD

**Issue by wzijden** [randdusing/cordova-plugin-bluetoothle#743]
hasPermissionBtScanAction and hasPermissionBtConnectAction should always return true on AndroidSDK < 31.

Otherwise it is very tricky to correctly implement these new permission checks needed for AndroidSDK 31.

**Comment by wzijden** [comment]
I have prepared a PR to fix this: https://github.com/randdusing/cordova-plugin-bluetoothle/pull/742

**Comment by randdusing** [comment]
Thanks, merged and will create a new release shortly
