### ISSUE TITLE
Samsung  Galaxy S3-S4-S5 different behavior

### ISSUE THREAD

**Issue by phice** [randdusing/cordova-plugin-bluetoothle#77]
Hi all,
I successfully implemented my BLE app and tested several devices like Samsung galaxy S3, Motorola moto G and moto E. When I tried testing samsung galaxy S4 and S5 the BLE is unable to discover services. I was thinking that was the OS but the motorola have the same android version of s4 and s5. 
any suggestion?

**Comment by randdusing** [comment]
@phice It's not possible to connect to an iOS device without previously scanning since the address is different per device. Are you still having the original issue? Please re-open if you are.
