### ISSUE TITLE
Error occoured when write a long string

### ISSUE THREAD

**Issue by WenWu92** [randdusing/cordova-plugin-bluetoothle#89]
Hi rand,
I'm trying to send a .bin file to the device for update the firmware, so I read and split the file to a 256 bytes length array, then send it via write(), but the errors occurred below:  

Error Domain=CBErrorDomain Code=0 "Unknown error." UserInfo=0x14ebbf80 {NSLocalizedDescription=Unknown error.}

Dose the write() function will limit the length of value?

**Comment by randdusing** [comment]
@WenWu92 You may want to try using writeQ with the type parameter set to ```noResponse```. It will automatically split into 20 byte packets and write as quickly as possible. Since noResponse isn't a reliable write, you'll want to do some error checking on the peripheral side to make sure nothing was corrupted.
