### ISSUE TITLE
Throughput

### ISSUE THREAD

**Issue by diverJohn** [randdusing/cordova-plugin-bluetoothle#98]
I'm writing an Android app, IOS next, which communicates with a TI CC2541.   I am also writing the code for the TI CC2541 so I have control of the code on both sides.  I am trying to increase the throughput when sending data from my app to the CC2541.   During initial development I had two CC2541s talking and was able to increase throughput by adjusting 3 things:

1) the connection interval
2) performing a write without response
3) filling 4 20-byte buffers for a max of 80 bytes per connection interval.  

Connection Interval:
When I send a request from my CC2541 to my Android phone to change the connection interval the phone does not change the connection interval.   When I was using 2 CC2541s I could change the connection interval down to 7.5 ms.   I know the minimum connection interval for IOS is 20 mS so I am asking for a 20 mS connection interval on the Android but it does not change.   The current connection interval on the Android phone is 48 mS as seen when I sniff the traffic.   Is there a way to set the initial connection interval from the plugin or is there a way to have the Android phone accept the change connection interval request?

WriteWithoutResponse:
According to issue #68 you added a "WriteWithoutResponse" type to the Write request.   Since I am using Phonegap Build the latest version of your plugin is 1.0.2.   You mention in #68 that you are trying to upload the latest version.  Have you uploaded the latest version to Phonegap and do you have an idea when it will be available?

Multi-byte buffers:
Sniffing the BLE traffic I see that my Android phone sends out an 18 byte packet and then waits for the response.   Do you know if there is a way to send multiple buffers per connection interval? 

The plugin is working great...I just need a little more speed for downloading large bin files...

Thanks,
John

**Comment by diverJohn** [comment]
Rand,
I noticed that #134 talks about throughput.   Have you had a chance to look at throughput issues lately?

**Comment by randdusing** [comment]
Take a look at #136. I'm looking at it right now. I migrated to Android Studio and updated Java, so I'm running into a ton of issues. Hopefully should be done tonight. 

With that said, I don't have the necessary hardware to test actual throughput. I'm mainly making sure everything else still works, adding in more error handlers and documenting it.

**Comment by diverJohn** [comment]
Good news...

I figured out how to get the multiple 20-byte buffers sent per connection interval and increased my throughput significantly.   Android phones allow up to 4 buffers to be written per connection interval and  IOS allows up to 6 buffers to be written per connection interval.   

My initial development was on an Android phone so when I did the WriteWithNoResponse I received a write success callback from the plugin which I thought meant that the data had been written to the hardware and that the hardware was ready for additional data so I waited before sending the next chunk of data, see issue #131.   Note that IOS does not send back the write success callback.    If I ignore the write success callback and just write multiple 20-byte chunks of data to the plugin, 4 in a row for Android, 6 in a row for IOS, then multiple buffers are written per connection interval and throughput increases.

One difference that I noticed between Android and IOS is that the write can take 5 to 10 mS on Android whereas a write on IOS returns in under 1 mS.   Is there a reason that a write on Android takes more time than a write on IOS?   This was consistent across multiple phones.

**Comment by diverJohn** [comment]
Rand,
Are there any coding differences between Android and IOS that would cause the write times to be so different or do you think that this is an OS difference?

**Comment by randdusing** [comment]
Not anything I can think of, it's pretty straightforward for both APIs.

**Comment by randdusing** [comment]
I've added the writeQ function which will automatically split data into 20byte packets and write them as quickly as possible on Android and iOS. Not much of a throughput improvement on iOS, but Android works much better.
