### ISSUE TITLE
Callbacks are not called in certain circumstances, leaving calling script in undefined condition!

### ISSUE THREAD

**Issue by jhpetersen** [randdusing/cordova-plugin-bluetoothle#99]
Problem:
Under certain circumstances none of the callback functions supplied to a plugin method is called, which leaves the calling script in a dead end waiting for eternity!

Cause:
Digging in your source code shows that on nearly every public plugin method you first check some criteria (which does make sense) but then immediately end the method with only "return" if a criterion is not met. This is critical as the calling script does except either the success or the error callback is called!
(For example think of the write command executed if the device is not properly connected..)

Solution:
Please ensure that in all callable plugin methods at least one callback gets fired! If the method cannot succeed properly call the error callback before exiting the method!

**Comment by randdusing** [comment]
Still having an issue with this?

**Comment by jhpetersen** [comment]
As i said, i forked the code in november 2014 and made same changes to the code. With this version i don't seem to have problems. So i can't say if i still would encounter the problem in your actual code version. But thanks for asking. 

Btw something completely different: in my fork i added code to the android sources to read the device name directly from the advertisement data. This seems to be neccessary on some Android phones as sometimes the device name provided from the getName() function is null.

**Comment by randdusing** [comment]
Thanks. I need to improve the advertisement data handling and will take a look at yours

**Comment by hunterdowns** [comment]
I'm having a similar problem on iOS using the characteristics callback.  In my application, I want to be able to get all the characteristics for all the services a peripheral has before returning to the application logic.  To do this, I'm using Promises: basically, I discover the list of services (works fine), then I create a promise for each service to discover the characteristic for the services and finally, I use Promise.all() with the array of promises.  HOWEVER, only the "successful" callback for the first bluetoothle.characteristics gets called and, as expected, only has the characteristics for the first service in the returned object.

```javascript
var discoverCharacteristicsIOS = function(params) {
    return new Promise(function (resolve, reject) {

       var success = function (obj) {

          console.log('discoverCharacteristicsIOS:success: ') ;

           if (obj.status == "characteristics") {
              // Resolve with the object
              console.log('discoverCharacteristicsIOS:success: Got characteristics '+ JSON.stringify(obj)) ;
              resolve(obj);
            } else {
               console.log('discoverCharacteristicsIOS:success: Unexpected status ' + JSON.stringify(obj)) ;
                resolve(obj) ;
            }
      };

      var failure = function (obj) {
          reject("discoverCharacteristicsIOS:failure : " + JSON.stringify(obj));

       };

       console.log("discoverCharacteristicsIOS : " + JSON.stringify(params));

       window.bluetoothle.characteristics(success, failure, params);

   );

} ;

// Return a promise for each characteristic
var servicesToCharacteristicPromise = function (service) {
      var charParams = {address: params.address, serviceUuid: service};
      return discoverCharacteristicsIOS(charParams);

 };



// Returns an array with a promise for each characteristic
var charPromiseArray = obj.serviceUuids.map(servicesToCharacteristicPromise);

console.log('DiscoverIOS:success: charPromiseArray length = ' + charPromiseArray.length);

// Get all the characteristics for all the services as an array of promises
Promise.all(charPromiseArray).then(charGetPass,charGetFail) ;
```

I've rewritten and tested this several ways and the bottom line seems to be that, if you haven't gotten the callback for the first service characteristics discovery, and you add requests to get discover more service characteristics, you won't get anymore after the first one.

So the question I have, is given that I want to return control back to the main execution loop after all services' characteristics have been discovered, how can can I do that? Alternatively, what's the possibility of having a characteristics() function like the services() one i.e. where your plugin does the discovery on all characteristics for a list of services UUIDs provided?

**Comment by randdusing** [comment]
Yah, the characteristics callback doesn't support simulataneous calls. I
really just need to implement discover for iOS and mimic the Android
functionality. There's another issue for it somewhere. Let me take a look
in the next few days. It shouldn't be too difficult or time consuming to
implement. By the way, Apple doesn't recommend discovering all the services
and characteristics, but it may make sense in some instances. I believe
this is due to performance reasons. Another possibility is passing a
hierarchy of services, characteristics and descriptor uuids so that iOS
only discovers what is necessary. This should address the possible
performance issues and make it simpler for the developer.

**Comment by hunterdowns** [comment]
Thanks for the quick response.  Yeah, unfortunately, despite performance challenges, I have to discover everything now...although I'm looking at changing this. 

Writing my comment earlier helped me figure out an alternative with just one promise and chaining through the services within the callback structure...not ideal but working now.

Mil gracias!

**Comment by randdusing** [comment]
@jhpetersen I wish I would have remembered this issue when deciding to implement clearOperationCallbacks recently...

The main branch returns most callbacks on disconnect in the master branch as of a few minor versions ago. In the 4.0.0 branch, all callbacks are returned on disconnect.

Also there's a comment about improved advertising data in an earlier post. Android and iOS both now return as much advertisement data as possible.
